select a.*
from GPROD1V_INP.TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN a
left join GPROD1T_BASE.ADDR b
	on  a.ADDR_ID=b.ADDR_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG_IN a
left join GPROD1T_BASE.DEMOG b
	on  a.DEMOG_CD=b.DEMOG_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY_IN a
left join GPROD1T_BASE.GEOGRCL_AREA b
	on  a.GEOGRCL_AREA_ID=b.GEOGRCL_AREA_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY_IN a
left join GPROD1T_BASE.GEOGRCL_AREA_RLTD b
	on  a.GEOGRCL_AREA_ID=b.GEOGRCL_AREA_ID 
	and a.RLTD_GEOGRCL_AREA_ID=b.RLTD_GEOGRCL_AREA_ID 
	and a.GEOGRCL_AREA_STRT_DTTM=b.GEOGRCL_AREA_STRT_DTTM 
	and a.GEOGRCL_AREA_RLTD_ROLE_ID=b.GEOGRCL_AREA_RLTD_ROLE_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG_IN a
left join GPROD1T_BASE.INDIV_DISEASE_STS b
	on  a.DISEASE_STS_STRT_DT=b.DISEASE_STS_STRT_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
	and a.DISEASE_REGISTRY_ID=b.DISEASE_REGISTRY_ID 
	and a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.DISEASE_STS_TYPE_CD=b.DISEASE_STS_TYPE_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG_IN a
left join GPROD1T_BASE.INDIV_DISEASE_STS b
	on  a.DISEASE_STS_STRT_DT=b.DISEASE_STS_STRT_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
	and a.DISEASE_REGISTRY_ID=b.DISEASE_REGISTRY_ID 
	and a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.DISEASE_STS_TYPE_CD=b.DISEASE_STS_TYPE_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT_IN a
left join GPROD1T_BASE.INDIV_DISEASE_STS b
	on  a.DISEASE_STS_STRT_DT=b.DISEASE_STS_STRT_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
	and a.DISEASE_REGISTRY_ID=b.DISEASE_REGISTRY_ID 
	and a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.DISEASE_STS_TYPE_CD=b.DISEASE_STS_TYPE_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT_IN a
left join GPROD1T_BASE.INDIV_MEDCL_MSR b
	on  a.DATA_SRC_TYPE_CD=b.DATA_SRC_TYPE_CD 
	and a.MEDCL_MSR_TYPE_CD=b.MEDCL_MSR_TYPE_CD 
	and a.MEDCL_HIST_DT=b.MEDCL_HIST_DT 
	and a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS_IN a
left join GPROD1T_BASE.INDIV_NAME b
	on  a.INDIV_PRTY_ID=b.INDIV_PRTY_ID 
	and a.NAME_TYPE_CD=b.NAME_TYPE_CD 
	and a.INDIV_NAME_STRT_DT=b.INDIV_NAME_STRT_DT 
	and a.DATA_SRC_CD=b.DATA_SRC_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY_IN a
left join GPROD1T_BASE.LOCTR b
	on  a.LOCTR_ID=b.LOCTR_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN a
left join GPROD1T_BASE.LOCTR b
	on  a.LOCTR_ID=b.LOCTR_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS_IN a
left join GPROD1T_BASE.ORG b
	on  a.ORG_PRTY_ID=b.ORG_PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS_IN a
left join GPROD1T_BASE.ORG_NAME b
	on  a.ORG_PRTY_ID=b.ORG_PRTY_ID 
	and a.NAME_TYPE_CD=b.NAME_TYPE_CD 
	and a.ORG_NAME_STRT_DT=b.ORG_NAME_STRT_DT 
	and a.DATA_SRC_CD=b.DATA_SRC_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS_IN a
left join GPROD1T_BASE.PRTY b
	on  a.PRTY_ID=b.PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS_IN a
left join GPROD1T_BASE.PRTY b
	on  a.PRTY_ID=b.PRTY_ID 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG_IN a
left join GPROD1T_BASE.PRTY_DEMOG b
	on  a.PRTY_ID=b.PRTY_ID 
	and a.DEMOG_CD=b.DEMOG_CD 
	and a.PRTY_DEMOG_STRT_DT=b.PRTY_DEMOG_STRT_DT 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN a
left join GPROD1T_BASE.PRTY_LOCTR b
	on  a.PRTY_ID=b.PRTY_ID 
	and a.LOCTR_ID=b.LOCTR_ID 
	and a.PRTY_LOCTR_STRT_DTTM=b.PRTY_LOCTR_STRT_DTTM 
	and a.PRTY_LOCTR_USGE_CD=b.PRTY_LOCTR_USGE_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY_IN a
left join GPROD1T_BASE.PRTY_LOCTR b
	on  a.PRTY_ID=b.PRTY_ID 
	and a.LOCTR_ID=b.LOCTR_ID 
	and a.PRTY_LOCTR_STRT_DTTM=b.PRTY_LOCTR_STRT_DTTM 
	and a.PRTY_LOCTR_USGE_CD=b.PRTY_LOCTR_USGE_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM_IN a
left join GPROD1T_BASE.PRTY_RLTD b
	on  a.PRTY_ID=b.PRTY_ID 
	and a.RLTD_PRTY_ID=b.RLTD_PRTY_ID 
	and a.RLTD_ROLE_CD=b.RLTD_ROLE_CD 
	and a.PRTY_RLTD_STRT_DTTM=b.PRTY_RLTD_STRT_DTTM 
	and a.DATA_SRC_CD=b.DATA_SRC_CD 
where b.process_name is null;

select a.*
from GPROD1V_INP.TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN a
left join GPROD1T_BASE.TLPHN_NUM b
	on  a.TLPHN_NUM_ID=b.TLPHN_NUM_ID 
where b.process_name is null;

