---PROCESS_CHECK_Test_Case_1---
SELECT * FROM GPROD1T_BASE.PRTY WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS' ;
 
---PROCESS_CHECK_Test_Case_2---
SELECT * FROM GPROD1T_BASE.ORG WHERE PROCESS_NAME = 'TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS' ;
 
---PROCESS_CHECK_Test_Case_3---
SELECT * FROM GPROD1T_BASE.ORG_NAME WHERE PROCESS_NAME = 'TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS' ;
 
---PROCESS_CHECK_Test_Case_4---
SELECT * FROM GPROD1T_BASE.LOCTR WHERE PROCESS_NAME = 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY' ;
 
---PROCESS_CHECK_Test_Case_5---
SELECT * FROM GPROD1T_BASE.GEOGRCL_AREA WHERE PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY' ;
 
---PROCESS_CHECK_Test_Case_6---
SELECT * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY' ;
 
---PROCESS_CHECK_Test_Case_7---
SELECT * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY' ;
 
---PROCESS_CHECK_Test_Case_8---
SELECT * FROM GPROD1T_BASE.PRTY WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS' ;
 
---PROCESS_CHECK_Test_Case_9---
SELECT * FROM GPROD1T_BASE.INDIV_NAME WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS' ;
 
---PROCESS_CHECK_Test_Case_10---
SELECT * FROM GPROD1T_BASE.LOCTR WHERE PROCESS_NAME = 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' ;
 
---PROCESS_CHECK_Test_Case_11---
SELECT * FROM GPROD1T_BASE.ADDR WHERE PROCESS_NAME = 'TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' ;
 
---PROCESS_CHECK_Test_Case_12---
SELECT * FROM GPROD1T_BASE.TLPHN_NUM WHERE PROCESS_NAME = 'TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' ;
 
---PROCESS_CHECK_Test_Case_13---
SELECT * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' ;
 
---PROCESS_CHECK_Test_Case_14---
SELECT * FROM GPROD1T_BASE.PRTY_RLTD WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM' ;
 
---PROCESS_CHECK_Test_Case_15---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG' ;
 
---PROCESS_CHECK_Test_Case_16---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG' ;
 
---PROCESS_CHECK_Test_Case_17---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT' ;
 
---PROCESS_CHECK_Test_Case_18---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE' ;
 
---PROCESS_CHECK_Test_Case_19---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE' ;
 
---PROCESS_CHECK_Test_Case_20---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR' ;
 
---PROCESS_CHECK_Test_Case_21---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT' ;
 
---PROCESS_CHECK_Test_Case_22---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT' ;
 
---PROCESS_CHECK_Test_Case_23---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT' ;
 
---PROCESS_CHECK_Test_Case_24---
SELECT * FROM GPROD1T_BASE.DEMOG WHERE PROCESS_NAME = 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG' ;
 
---PROCESS_CHECK_Test_Case_25---
SELECT * FROM GPROD1T_BASE.PRTY_DEMOG WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG' ;
 
