---bmap_check_Test_Case_1---
SEL GPROD1T_BASE.PRTY.PRTY_SBTYPE_CD,GPROD1T_BASE.PRTY.PRTY_ID
 FROM GPROD1T_BASE.PRTY LEFT JOIN GPROD1T_BASE.PRTY_SBTYPE
 ON GPROD1T_BASE.PRTY.PRTY_SBTYPE_CD=GPROD1T_BASE.PRTY_SBTYPE.PRTY_SBTYPE_CD
 WHERE GPROD1T_BASE.PRTY_SBTYPE.PRTY_SBTYPE_CD;


---bmap_check_Test_Case_2---
SEL GPROD1T_BASE.PRTY.PRTY_TYPE_CD,GPROD1T_BASE.PRTY.PRTY_ID
 FROM GPROD1T_BASE.PRTY LEFT JOIN GPROD1T_BASE.PRTY_TYPE
 ON GPROD1T_BASE.PRTY.PRTY_TYPE_CD=GPROD1T_BASE.PRTY_TYPE.PRTY_TYPE_CD
 WHERE GPROD1T_BASE.PRTY_TYPE.PRTY_TYPE_CD;


---bmap_check_Test_Case_3---
SEL GPROD1T_BASE.ORG.ORG_SBTYPE_CD,GPROD1T_BASE.ORG.ORG_PRTY_ID
 FROM GPROD1T_BASE.ORG LEFT JOIN GPROD1T_BASE.ORG_SBTYPE
 ON GPROD1T_BASE.ORG.ORG_SBTYPE_CD=GPROD1T_BASE.ORG_SBTYPE.ORG_SBTYPE_CD
 WHERE GPROD1T_BASE.ORG_SBTYPE.ORG_SBTYPE_CD;


---bmap_check_Test_Case_4---
SEL GPROD1T_BASE.ORG.LEGL_CLASFCN_CD,GPROD1T_BASE.ORG.ORG_PRTY_ID
 FROM GPROD1T_BASE.ORG LEFT JOIN GPROD1T_BASE.LEGL_CLASFCN
 ON GPROD1T_BASE.ORG.LEGL_CLASFCN_CD=GPROD1T_BASE.LEGL_CLASFCN.LEGL_CLASFCN_CD
 WHERE GPROD1T_BASE.LEGL_CLASFCN.LEGL_CLASFCN_CD;


---bmap_check_Test_Case_5---
SEL GPROD1T_BASE.ORG.DATA_SRC_CD,GPROD1T_BASE.ORG.ORG_PRTY_ID
 FROM GPROD1T_BASE.ORG LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.ORG.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


---bmap_check_Test_Case_6---
SEL GPROD1T_BASE.ORG_NAME.NAME_TYPE_CD,GPROD1T_BASE.ORG_NAME.ORG_PRTY_ID
 FROM GPROD1T_BASE.ORG_NAME LEFT JOIN GPROD1T_BASE.NAME_TYPE
 ON GPROD1T_BASE.ORG_NAME.NAME_TYPE_CD=GPROD1T_BASE.NAME_TYPE.NAME_TYPE_CD
 WHERE GPROD1T_BASE.NAME_TYPE.NAME_TYPE_CD;


---bmap_check_Test_Case_7---
SEL GPROD1T_BASE.ORG_NAME.DATA_SRC_CD,GPROD1T_BASE.ORG_NAME.ORG_PRTY_ID
 FROM GPROD1T_BASE.ORG_NAME LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.ORG_NAME.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


---bmap_check_Test_Case_8---
SEL GPROD1T_BASE.LOCTR.LOCTR_SBTYPE_CD,GPROD1T_BASE.LOCTR.LOCTR_ID
 FROM GPROD1T_BASE.LOCTR LEFT JOIN GPROD1T_BASE.LOCTR_SBTYPE
 ON GPROD1T_BASE.LOCTR.LOCTR_SBTYPE_CD=GPROD1T_BASE.LOCTR_SBTYPE.LOCTR_SBTYPE_CD
 WHERE GPROD1T_BASE.LOCTR_SBTYPE.LOCTR_SBTYPE_CD;


---bmap_check_Test_Case_9---
SEL GPROD1T_BASE.GEOGRCL_AREA.GEOGRCL_AREA_SBTYPE_CD,GPROD1T_BASE.GEOGRCL_AREA.GEOGRCL_AREA_ID
 FROM GPROD1T_BASE.GEOGRCL_AREA LEFT JOIN GPROD1T_BASE.GEOGRCL_AREA_SBTYPE
 ON GPROD1T_BASE.GEOGRCL_AREA.GEOGRCL_AREA_SBTYPE_CD=GPROD1T_BASE.GEOGRCL_AREA_SBTYPE.GEOGRCL_AREA_SBTYPE_CD
 WHERE GPROD1T_BASE.GEOGRCL_AREA_SBTYPE.GEOGRCL_AREA_SBTYPE_CD;


---bmap_check_Test_Case_10---
SEL GPROD1T_BASE.PRTY_LOCTR.PRTY_LOCTR_USGE_CD,GPROD1T_BASE.PRTY_LOCTR.PRTY_ID
 FROM GPROD1T_BASE.PRTY_LOCTR LEFT JOIN GPROD1T_BASE.PRTY_LOCTR_USGE
 ON GPROD1T_BASE.PRTY_LOCTR.PRTY_LOCTR_USGE_CD=GPROD1T_BASE.PRTY_LOCTR_USGE.PRTY_LOCTR_USGE_CD
 WHERE GPROD1T_BASE.PRTY_LOCTR_USGE.PRTY_LOCTR_USGE_CD;


---bmap_check_Test_Case_11---
SEL GPROD1T_BASE.INDIV_NAME.NAME_TYPE_CD,GPROD1T_BASE.INDIV_NAME.INDIV_PRTY_ID
 FROM GPROD1T_BASE.INDIV_NAME LEFT JOIN GPROD1T_BASE.NAME_TYPE
 ON GPROD1T_BASE.INDIV_NAME.NAME_TYPE_CD=GPROD1T_BASE.NAME_TYPE.NAME_TYPE_CD
 WHERE GPROD1T_BASE.NAME_TYPE.NAME_TYPE_CD;


---bmap_check_Test_Case_12---
SEL GPROD1T_BASE.INDIV_NAME.DATA_SRC_CD,GPROD1T_BASE.INDIV_NAME.INDIV_PRTY_ID
 FROM GPROD1T_BASE.INDIV_NAME LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.INDIV_NAME.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


---bmap_check_Test_Case_13---
SEL GPROD1T_BASE.ADDR.ADDR_SBTYPE_CD,GPROD1T_BASE.ADDR.ADDR_ID
 FROM GPROD1T_BASE.ADDR LEFT JOIN GPROD1T_BASE.ADDR_SBTYPE
 ON GPROD1T_BASE.ADDR.ADDR_SBTYPE_CD=GPROD1T_BASE.ADDR_SBTYPE.ADDR_SBTYPE_CD
 WHERE GPROD1T_BASE.ADDR_SBTYPE.ADDR_SBTYPE_CD;


---bmap_check_Test_Case_14---
SEL GPROD1T_BASE.PRTY_RLTD.DATA_SRC_CD,GPROD1T_BASE.PRTY_RLTD.PRTY_ID
 FROM GPROD1T_BASE.PRTY_RLTD LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.PRTY_RLTD.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


---bmap_check_Test_Case_15---
SEL GPROD1T_BASE.INDIV_DISEASE_STS.DISEASE_STS_TYPE_CD,GPROD1T_BASE.INDIV_DISEASE_STS.INDIV_PRTY_ID
 FROM GPROD1T_BASE.INDIV_DISEASE_STS LEFT JOIN GPROD1T_BASE.DISEASE_STS_TYPE
 ON GPROD1T_BASE.INDIV_DISEASE_STS.DISEASE_STS_TYPE_CD=GPROD1T_BASE.DISEASE_STS_TYPE.DISEASE_STS_TYPE_CD
 WHERE GPROD1T_BASE.DISEASE_STS_TYPE.DISEASE_STS_TYPE_CD;


---bmap_check_Test_Case_16---
SEL GPROD1T_BASE.INDIV_MEDCL_MSR.MEDCL_MSR_TYPE_CD,GPROD1T_BASE.INDIV_MEDCL_MSR.INDIV_PRTY_ID
 FROM GPROD1T_BASE.INDIV_MEDCL_MSR LEFT JOIN GPROD1T_BASE.MEDCL_MSR_TYPE
 ON GPROD1T_BASE.INDIV_MEDCL_MSR.MEDCL_MSR_TYPE_CD=GPROD1T_BASE.MEDCL_MSR_TYPE.MEDCL_MSR_TYPE_CD
 WHERE GPROD1T_BASE.MEDCL_MSR_TYPE.MEDCL_MSR_TYPE_CD;


---bmap_check_Test_Case_17---
SEL GPROD1T_BASE.DEMOG.DEMOG_GRP_CD,GPROD1T_BASE.DEMOG.SRC_ORG_PRTY_ID
 FROM GPROD1T_BASE.DEMOG LEFT JOIN GPROD1T_BASE.DEMOG_GRP
 ON GPROD1T_BASE.DEMOG.DEMOG_GRP_CD=GPROD1T_BASE.DEMOG_GRP.DEMOG_GRP_CD
 WHERE GPROD1T_BASE.DEMOG_GRP.DEMOG_GRP_CD;


---bmap_check_Test_Case_18---
SEL GPROD1T_BASE.DEMOG.DATA_SRC_CD,GPROD1T_BASE.DEMOG.SRC_ORG_PRTY_ID
 FROM GPROD1T_BASE.DEMOG LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.DEMOG.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


---bmap_check_Test_Case_19---
SEL GPROD1T_BASE.PRTY_DEMOG.DATA_SRC_CD,GPROD1T_BASE.PRTY_DEMOG.PRTY_ID
 FROM GPROD1T_BASE.PRTY_DEMOG LEFT JOIN GPROD1T_BASE.DATA_SRC_TYPE
 ON GPROD1T_BASE.PRTY_DEMOG.DATA_SRC_CD=GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
 WHERE GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD;


