---bmap_null_check_Test_Case_1---
SEL * FROM GPROD1T_BASE.PRTY_SBTYPE WHERE PRTY_SBTYPE_CD IS NULL OR PRTY_SBTYPE_DESC IS NULL;


---bmap_null_check_Test_Case_2---
SEL * FROM GPROD1T_BASE.PRTY_TYPE WHERE PRTY_TYPE_CD IS NULL OR PRTY_TYPE_DESC IS NULL;


---bmap_null_check_Test_Case_3---
SEL * FROM GPROD1T_BASE.ORG_SBTYPE WHERE ORG_SBTYPE_CD IS NULL OR ORG_SBTYPE_DESC IS NULL;


---bmap_null_check_Test_Case_4---
SEL * FROM GPROD1T_BASE.LEGL_CLASFCN WHERE LEGL_CLASFCN_CD IS NULL OR LEGL_CLASFCN_DESC IS NULL;


---bmap_null_check_Test_Case_5---
SEL * FROM GPROD1T_BASE.DATA_SRC_TYPE WHERE DATA_SRC_CD IS NULL OR DATA_SRC_DESC IS NULL;


---bmap_null_check_Test_Case_6---
SEL * FROM GPROD1T_BASE.NAME_TYPE WHERE NAME_TYPE_CD IS NULL OR NAME_TYPE_DESC IS NULL;


---bmap_null_check_Test_Case_7---
SEL * FROM GPROD1T_BASE.LOCTR_SBTYPE WHERE LOCTR_SBTYPE_CD IS NULL OR LOCTR_SBTYPE_DESC IS NULL;


---bmap_null_check_Test_Case_8---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA_SBTYPE WHERE GEOGRCL_AREA_SBTYPE_CD IS NULL OR GEOGRCL_AREA_SBTYPE_DESC IS NULL;


---bmap_null_check_Test_Case_9---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR_USGE WHERE PRTY_LOCTR_USGE_CD IS NULL OR PRTY_LOCTR_USGE_DESC IS NULL;


---bmap_null_check_Test_Case_10---
SEL * FROM GPROD1T_BASE.ADDR_SBTYPE WHERE ADDR_SBTYPE_CD IS NULL OR ADDR_SBTYPE_DESC IS NULL;


---bmap_null_check_Test_Case_11---
SEL * FROM GPROD1T_BASE.DISEASE_STS_TYPE WHERE DISEASE_STS_TYPE_CD IS NULL OR DISEASE_STS_TYPE_DESC IS NULL;


---bmap_null_check_Test_Case_12---
SEL * FROM GPROD1T_BASE.MEDCL_MSR_TYPE WHERE MEDCL_MSR_TYPE_CD IS NULL OR MEDCL_MSR_TYPE_DESC IS NULL;


---bmap_null_check_Test_Case_13---
SEL * FROM GPROD1T_BASE.DEMOG_GRP WHERE DEMOG_GRP_CD IS NULL OR DEMOG_GRP_DESC IS NULL;


