---bmap_dup_cd_check_Test_Case_1---
SEL PRTY_SBTYPE_CD FROM GPROD1T_BASE.PRTY_SBTYPE GROUP BY PRTY_SBTYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_2---
SEL PRTY_TYPE_CD FROM GPROD1T_BASE.PRTY_TYPE GROUP BY PRTY_TYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_3---
SEL ORG_SBTYPE_CD FROM GPROD1T_BASE.ORG_SBTYPE GROUP BY ORG_SBTYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_4---
SEL LEGL_CLASFCN_CD FROM GPROD1T_BASE.LEGL_CLASFCN GROUP BY LEGL_CLASFCN_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_5---
SEL DATA_SRC_CD FROM GPROD1T_BASE.DATA_SRC_TYPE GROUP BY DATA_SRC_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_6---
SEL NAME_TYPE_CD FROM GPROD1T_BASE.NAME_TYPE GROUP BY NAME_TYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_7---
SEL LOCTR_SBTYPE_CD FROM GPROD1T_BASE.LOCTR_SBTYPE GROUP BY LOCTR_SBTYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_8---
SEL GEOGRCL_AREA_SBTYPE_CD FROM GPROD1T_BASE.GEOGRCL_AREA_SBTYPE GROUP BY GEOGRCL_AREA_SBTYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_9---
SEL PRTY_LOCTR_USGE_CD FROM GPROD1T_BASE.PRTY_LOCTR_USGE GROUP BY PRTY_LOCTR_USGE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_10---
SEL ADDR_SBTYPE_CD FROM GPROD1T_BASE.ADDR_SBTYPE GROUP BY ADDR_SBTYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_11---
SEL DISEASE_STS_TYPE_CD FROM GPROD1T_BASE.DISEASE_STS_TYPE GROUP BY DISEASE_STS_TYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_12---
SEL MEDCL_MSR_TYPE_CD FROM GPROD1T_BASE.MEDCL_MSR_TYPE GROUP BY MEDCL_MSR_TYPE_CD HAVING COUNT(*)>1;


---bmap_dup_cd_check_Test_Case_13---
SEL DEMOG_GRP_CD FROM GPROD1T_BASE.DEMOG_GRP GROUP BY DEMOG_GRP_CD HAVING COUNT(*)>1;


