---bmap_dup_check_desc_Test_Case_1---
SEL PRTY_SBTYPE_DESC FROM GPROD1T_BASE.PRTY_SBTYPE GROUP BY PRTY_SBTYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_2---
SEL PRTY_TYPE_DESC FROM GPROD1T_BASE.PRTY_TYPE GROUP BY PRTY_TYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_3---
SEL ORG_SBTYPE_DESC FROM GPROD1T_BASE.ORG_SBTYPE GROUP BY ORG_SBTYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_4---
SEL LEGL_CLASFCN_DESC FROM GPROD1T_BASE.LEGL_CLASFCN GROUP BY LEGL_CLASFCN_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_5---
SEL DATA_SRC_DESC FROM GPROD1T_BASE.DATA_SRC_TYPE GROUP BY DATA_SRC_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_6---
SEL NAME_TYPE_DESC FROM GPROD1T_BASE.NAME_TYPE GROUP BY NAME_TYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_7---
SEL LOCTR_SBTYPE_DESC FROM GPROD1T_BASE.LOCTR_SBTYPE GROUP BY LOCTR_SBTYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_8---
SEL GEOGRCL_AREA_SBTYPE_DESC FROM GPROD1T_BASE.GEOGRCL_AREA_SBTYPE GROUP BY GEOGRCL_AREA_SBTYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_9---
SEL PRTY_LOCTR_USGE_DESC FROM GPROD1T_BASE.PRTY_LOCTR_USGE GROUP BY PRTY_LOCTR_USGE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_10---
SEL ADDR_SBTYPE_DESC FROM GPROD1T_BASE.ADDR_SBTYPE GROUP BY ADDR_SBTYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_11---
SEL DISEASE_STS_TYPE_DESC FROM GPROD1T_BASE.DISEASE_STS_TYPE GROUP BY DISEASE_STS_TYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_12---
SEL MEDCL_MSR_TYPE_DESC FROM GPROD1T_BASE.MEDCL_MSR_TYPE GROUP BY MEDCL_MSR_TYPE_DESC HAVING COUNT(*)>1;


---bmap_dup_check_desc_Test_Case_13---
SEL DEMOG_GRP_DESC FROM GPROD1T_BASE.DEMOG_GRP GROUP BY DEMOG_GRP_DESC HAVING COUNT(*)>1;


