---bmap_null_check_Test_Case_1---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(PRTY_SBTYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.PRTY_SBTYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.PRTY_SBTYPE.PRTY_SBTYPE_CD
WHERE EDW_CODE IS NULL OR PRTY_SBTYPE_CD IS NULL AND CODE_SET_ID = 15


---bmap_null_check_Test_Case_2---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(PRTY_TYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.PRTY_TYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.PRTY_TYPE.PRTY_TYPE_CD
WHERE EDW_CODE IS NULL OR PRTY_TYPE_CD IS NULL AND CODE_SET_ID = 16


---bmap_null_check_Test_Case_3---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(ORG_SBTYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.ORG_SBTYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.ORG_SBTYPE.ORG_SBTYPE_CD
WHERE EDW_CODE IS NULL OR ORG_SBTYPE_CD IS NULL AND CODE_SET_ID = 68


---bmap_null_check_Test_Case_4---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(LEGL_CLASFCN_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.LEGL_CLASFCN
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.LEGL_CLASFCN.LEGL_CLASFCN_CD
WHERE EDW_CODE IS NULL OR LEGL_CLASFCN_CD IS NULL AND CODE_SET_ID = 5


---bmap_null_check_Test_Case_5---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(DATA_SRC_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.DATA_SRC_TYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.DATA_SRC_TYPE.DATA_SRC_CD
WHERE EDW_CODE IS NULL OR DATA_SRC_CD IS NULL AND CODE_SET_ID = 1


---bmap_null_check_Test_Case_6---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(NAME_TYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.NAME_TYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.NAME_TYPE.NAME_TYPE_CD
WHERE EDW_CODE IS NULL OR NAME_TYPE_CD IS NULL AND CODE_SET_ID = 7


---bmap_null_check_Test_Case_7---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(LOCTR_SBTYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.LOCTR_SBTYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.LOCTR_SBTYPE.LOCTR_SBTYPE_CD
WHERE EDW_CODE IS NULL OR LOCTR_SBTYPE_CD IS NULL AND CODE_SET_ID = 38


---bmap_null_check_Test_Case_8---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(GEOGRCL_AREA_SBTYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.GEOGRCL_AREA_SBTYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.GEOGRCL_AREA_SBTYPE.GEOGRCL_AREA_SBTYPE_CD
WHERE EDW_CODE IS NULL OR GEOGRCL_AREA_SBTYPE_CD IS NULL AND CODE_SET_ID = 19


---bmap_null_check_Test_Case_9---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(PRTY_LOCTR_USGE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.PRTY_LOCTR_USGE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.PRTY_LOCTR_USGE.PRTY_LOCTR_USGE_CD
WHERE EDW_CODE IS NULL OR PRTY_LOCTR_USGE_CD IS NULL AND CODE_SET_ID = 21


---bmap_null_check_Test_Case_10---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(ADDR_SBTYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.ADDR_SBTYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.ADDR_SBTYPE.ADDR_SBTYPE_CD
WHERE EDW_CODE IS NULL OR ADDR_SBTYPE_CD IS NULL AND CODE_SET_ID = 20


---bmap_null_check_Test_Case_11---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(DISEASE_STS_TYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.DISEASE_STS_TYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.DISEASE_STS_TYPE.DISEASE_STS_TYPE_CD
WHERE EDW_CODE IS NULL OR DISEASE_STS_TYPE_CD IS NULL AND CODE_SET_ID = 89


---bmap_null_check_Test_Case_12---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(MEDCL_MSR_TYPE_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.MEDCL_MSR_TYPE
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.MEDCL_MSR_TYPE.MEDCL_MSR_TYPE_CD
WHERE EDW_CODE IS NULL OR MEDCL_MSR_TYPE_CD IS NULL AND CODE_SET_ID = 90


---bmap_null_check_Test_Case_13---
SEL COALESCE(EDW_CODE,'NOT IN BMAP TABLE BUT IN BASE TABLE')AS EDW_CODE,
SEL COALESCE(DEMOG_GRP_CD,'NOT IN BASE TABLE BUT IN BMAP TABLE')AS BASE_CODE
 FROM GPROD1V_UTLFW.BMAP_STANDARD_MAP FULL OUTER JOIN GPROD1T_BASE.DEMOG_GRP
ON GPROD1V_UTLFW.BMAP_STANDARD_MAP.EDW_CODE = GPROD1T_BASE.DEMOG_GRP.DEMOG_GRP_CD
WHERE EDW_CODE IS NULL OR DEMOG_GRP_CD IS NULL AND CODE_SET_ID = 3


