---hist_timegap_Test_Case_1---
SELECT GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_RLTD_ROLE_ID,GEOGRCL_AREA_STRT_DTTM,end_
FROM ( sel GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_RLTD_ROLE_ID,GEOGRCL_AREA_STRT_DTTM,MAX(GEOGRCL_AREA_END_DTTM)over(partition by 
GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_RLTD_ROLE_ID order by GEOGRCL_AREA_STRT_DTTM rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD
WHERE PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.GEOGRCL_AREA_STRT_DTTM;


---hist_timegap_Test_Case_2---
SELECT PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,PRTY_LOCTR_STRT_DTTM,end_
FROM ( sel PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,PRTY_LOCTR_STRT_DTTM,MAX(PRTY_LOCTR_END_DTTM)over(partition by 
PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD order by PRTY_LOCTR_STRT_DTTM rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.PRTY_LOCTR
WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.PRTY_LOCTR_STRT_DTTM;


---hist_timegap_Test_Case_3---
SELECT PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,PRTY_LOCTR_STRT_DTTM,end_
FROM ( sel PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,PRTY_LOCTR_STRT_DTTM,MAX(PRTY_LOCTR_END_DTTM)over(partition by 
PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD order by PRTY_LOCTR_STRT_DTTM rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.PRTY_LOCTR
WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.PRTY_LOCTR_STRT_DTTM;


---hist_timegap_Test_Case_4---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,end_
FROM ( sel INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,MAX(DISEASE_STS_END_DT)over(partition by 
INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD order by DISEASE_STS_STRT_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_DISEASE_STS
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.DISEASE_STS_STRT_DT;


---hist_timegap_Test_Case_5---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,end_
FROM ( sel INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,MAX(DISEASE_STS_END_DT)over(partition by 
INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD order by DISEASE_STS_STRT_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_DISEASE_STS
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.DISEASE_STS_STRT_DT;


---hist_timegap_Test_Case_6---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,end_
FROM ( sel INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,MAX(DISEASE_STS_END_DT)over(partition by 
INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD order by DISEASE_STS_STRT_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_DISEASE_STS
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.DISEASE_STS_STRT_DT;


---hist_timegap_Test_Case_7---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_8---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_9---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_10---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_11---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_12---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,end_
FROM ( sel DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_HIST_DT,MAX(MEDCL_HIST_END_DT)over(partition by 
DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID order by MEDCL_HIST_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.INDIV_MEDCL_MSR
WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.MEDCL_HIST_DT;


---hist_timegap_Test_Case_13---
SELECT PRTY_ID,DEMOG_CD,PRTY_DEMOG_STRT_DT,end_
FROM ( sel PRTY_ID,DEMOG_CD,PRTY_DEMOG_STRT_DT,MAX(PRTY_DEMOG_END_DT)over(partition by 
PRTY_ID,DEMOG_CD order by PRTY_DEMOG_STRT_DT rows between 1 preceding and 1 preceding)as end_
FROM GPROD1T_BASE.PRTY_DEMOG
WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG')tst
WHERE tst.end_ + INTERVAL'1'DAY<>tst.PRTY_DEMOG_STRT_DT;


