---hist_start_gr_end_Test_Case_1---
SELECT * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE GEOGRCL_AREA_STRT_DTTM > GEOGRCL_AREA_END_DTTM
AND PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY' ;


---hist_start_gr_end_Test_Case_2---
SELECT * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_STRT_DTTM > PRTY_LOCTR_END_DTTM
AND PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY' ;


---hist_start_gr_end_Test_Case_3---
SELECT * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_STRT_DTTM > PRTY_LOCTR_END_DTTM
AND PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' ;


---hist_start_gr_end_Test_Case_4---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT > DISEASE_STS_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG' ;


---hist_start_gr_end_Test_Case_5---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT > DISEASE_STS_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG' ;


---hist_start_gr_end_Test_Case_6---
SELECT * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT > DISEASE_STS_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT' ;


---hist_start_gr_end_Test_Case_7---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE' ;


---hist_start_gr_end_Test_Case_8---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE' ;


---hist_start_gr_end_Test_Case_9---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR' ;


---hist_start_gr_end_Test_Case_10---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT' ;


---hist_start_gr_end_Test_Case_11---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT' ;


---hist_start_gr_end_Test_Case_12---
SELECT * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT > MEDCL_HIST_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT' ;


---hist_start_gr_end_Test_Case_13---
SELECT * FROM GPROD1T_BASE.PRTY_DEMOG WHERE PRTY_DEMOG_STRT_DT > PRTY_DEMOG_END_DT
AND PROCESS_NAME = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG' ;


