---hist_dup_Test_Case_1---
SELECT GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_RLTD_ROLE_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_STRT_DTTM,,GEOGRCL_AREA_END_DTTM
FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE 
PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY' 
GROUP BY GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_RLTD_ROLE_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_STRT_DTTM,GEOGRCL_AREA_END_DTTM
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_2---
SELECT PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,,PRTY_LOCTR_END_DTTM
FROM GPROD1T_BASE.PRTY_LOCTR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY' 
GROUP BY PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,PRTY_LOCTR_END_DTTM
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_3---
SELECT PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,,PRTY_LOCTR_END_DTTM
FROM GPROD1T_BASE.PRTY_LOCTR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER' 
GROUP BY PRTY_ID,LOCTR_ID,PRTY_LOCTR_USGE_CD,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,PRTY_LOCTR_END_DTTM
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_4---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,,DISEASE_STS_END_DT
FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG' 
GROUP BY INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,DISEASE_STS_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_5---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,,DISEASE_STS_END_DT
FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG' 
GROUP BY INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,DISEASE_STS_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_6---
SELECT INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,,DISEASE_STS_END_DT
FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT' 
GROUP BY INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_TYPE_CD,DISEASE_STS_STRT_DT,DISEASE_STS_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_7---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_8---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_9---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_10---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_11---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_12---
SELECT DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,,MEDCL_HIST_END_DT
FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE 
PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT' 
GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,INDIV_PRTY_ID,MEDCL_MSR_VAL,MEDCL_HIST_DT,MEDCL_HIST_END_DT
 HAVING COUNT(*)>1;


---hist_dup_Test_Case_13---
SELECT PRTY_ID,DEMOG_CD,DEMOG_CD,PRTY_DEMOG_STRT_DT,,PRTY_DEMOG_END_DT
FROM GPROD1T_BASE.PRTY_DEMOG WHERE 
PROCESS_NAME = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG' 
GROUP BY PRTY_ID,DEMOG_CD,DEMOG_CD,PRTY_DEMOG_STRT_DT,PRTY_DEMOG_END_DT
 HAVING COUNT(*)>1;


