---data_src_Test_Case_1---
SEL * FROM GPROD1T_BASE.DEMOG WHERE DEMOG_CD<>4 and process_name= 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';


---data_src_Test_Case_2---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_SBTYPE_CD<>46 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_3---
SEL * FROM GPROD1T_BASE.PRTY WHERE INIT_DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_4---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_TYPE_CD<>2 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_5---
SEL * FROM GPROD1T_BASE.ORG WHERE ORG_SBTYPE_CD<>22 and process_name= 'TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_6---
SEL * FROM GPROD1T_BASE.ORG WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_7---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE NAME_TYPE_CD<>44 and process_name= 'TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_8---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';


---data_src_Test_Case_9---
SEL * FROM GPROD1T_BASE.LOCTR WHERE LOCTR_SBTYPE_CD<>10 and process_name= 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY';


---data_src_Test_Case_10---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA WHERE GEOGRCL_AREA_SBTYPE_CD<>9 and process_name= 'TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY';


---data_src_Test_Case_11---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_USGE_CD<>59 and process_name= 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';


---data_src_Test_Case_12---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_SBTYPE_CD<>1 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS';


---data_src_Test_Case_13---
SEL * FROM GPROD1T_BASE.PRTY WHERE INIT_DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS';


---data_src_Test_Case_14---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_TYPE_CD<>1 and process_name= 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS';


---data_src_Test_Case_15---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE NAME_TYPE_CD<>49 and process_name= 'TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';


---data_src_Test_Case_16---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';


---data_src_Test_Case_17---
SEL * FROM GPROD1T_BASE.LOCTR WHERE LOCTR_SBTYPE_CD<>2 and process_name= 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';


---data_src_Test_Case_18---
SEL * FROM GPROD1T_BASE.ADDR WHERE ADDR_SBTYPE_CD<>5 and process_name= 'TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';


---data_src_Test_Case_19---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_USGE_CD<>62 and process_name= 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';


---data_src_Test_Case_20---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE RLTD_ROLE_CD<>89 and process_name= 'TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';


---data_src_Test_Case_21---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';


---data_src_Test_Case_22---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';


---data_src_Test_Case_23---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';


---data_src_Test_Case_24---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';


---data_src_Test_Case_25---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';


---data_src_Test_Case_26---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>1 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';


---data_src_Test_Case_27---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>10 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';


---data_src_Test_Case_28---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';


---data_src_Test_Case_29---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>2 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';


---data_src_Test_Case_30---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>10 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';


---data_src_Test_Case_31---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';


---data_src_Test_Case_32---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>5 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';


---data_src_Test_Case_33---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>13 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';


---data_src_Test_Case_34---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';


---data_src_Test_Case_35---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>6 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';


---data_src_Test_Case_36---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>14 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';


---data_src_Test_Case_37---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';


---data_src_Test_Case_38---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>3 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';


---data_src_Test_Case_39---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>11 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';


---data_src_Test_Case_40---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD<>31 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';


---data_src_Test_Case_41---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD<>4 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';


---data_src_Test_Case_42---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_UOM_CD<>12 and process_name= 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';


---data_src_Test_Case_43---
SEL * FROM GPROD1T_BASE.DEMOG WHERE DEMOG_GRP_CD<>2 and process_name= 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';


---data_src_Test_Case_44---
SEL * FROM GPROD1T_BASE.DEMOG WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';


---data_src_Test_Case_45---
SEL * FROM GPROD1T_BASE.PRTY_DEMOG WHERE DATA_SRC_CD<>31 and process_name= 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';


---data_src_Test_Case_46---
SEL * FROM GPROD1T_BASE.PRTY_DEMOG WHERE DEMOG_CD<>4 and process_name= 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';


