---Null_Test_Case_1---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS';

---Null_Test_Case_2---
SEL * FROM GPROD1T_BASE.ORG WHERE ORG_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS';

---Null_Test_Case_3---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE ORG_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';

---Null_Test_Case_4---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE NAME_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';

---Null_Test_Case_5---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE ORG_NAME_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';

---Null_Test_Case_6---
SEL * FROM GPROD1T_BASE.ORG_NAME WHERE DATA_SRC_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS';

---Null_Test_Case_7---
SEL * FROM GPROD1T_BASE.LOCTR WHERE LOCTR_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY';

---Null_Test_Case_8---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA WHERE GEOGRCL_AREA_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY';

---Null_Test_Case_9---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE GEOGRCL_AREA_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY';

---Null_Test_Case_10---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE RLTD_GEOGRCL_AREA_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY';

---Null_Test_Case_11---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE GEOGRCL_AREA_STRT_DTTM IS NULL AND PROCESS_NAME='TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY';

---Null_Test_Case_12---
SEL * FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD WHERE GEOGRCL_AREA_RLTD_ROLE_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY';

---Null_Test_Case_13---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';

---Null_Test_Case_14---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE LOCTR_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';

---Null_Test_Case_15---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_STRT_DTTM IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';

---Null_Test_Case_16---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_USGE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';

---Null_Test_Case_17---
SEL * FROM GPROD1T_BASE.PRTY WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS';

---Null_Test_Case_18---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';

---Null_Test_Case_19---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE NAME_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';

---Null_Test_Case_20---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE INDIV_NAME_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';

---Null_Test_Case_21---
SEL * FROM GPROD1T_BASE.INDIV_NAME WHERE DATA_SRC_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS';

---Null_Test_Case_22---
SEL * FROM GPROD1T_BASE.LOCTR WHERE LOCTR_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_23---
SEL * FROM GPROD1T_BASE.ADDR WHERE ADDR_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_24---
SEL * FROM GPROD1T_BASE.TLPHN_NUM WHERE TLPHN_NUM_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_25---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_26---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE LOCTR_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_27---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_STRT_DTTM IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_28---
SEL * FROM GPROD1T_BASE.PRTY_LOCTR WHERE PRTY_LOCTR_USGE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';

---Null_Test_Case_29---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';

---Null_Test_Case_30---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE RLTD_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';

---Null_Test_Case_31---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE RLTD_ROLE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';

---Null_Test_Case_32---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE PRTY_RLTD_STRT_DTTM IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';

---Null_Test_Case_33---
SEL * FROM GPROD1T_BASE.PRTY_RLTD WHERE DATA_SRC_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM';

---Null_Test_Case_34---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';

---Null_Test_Case_35---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';

---Null_Test_Case_36---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_REGISTRY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';

---Null_Test_Case_37---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';

---Null_Test_Case_38---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';

---Null_Test_Case_39---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';

---Null_Test_Case_40---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';

---Null_Test_Case_41---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_REGISTRY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';

---Null_Test_Case_42---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';

---Null_Test_Case_43---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';

---Null_Test_Case_44---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';

---Null_Test_Case_45---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';

---Null_Test_Case_46---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_REGISTRY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';

---Null_Test_Case_47---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';

---Null_Test_Case_48---
SEL * FROM GPROD1T_BASE.INDIV_DISEASE_STS WHERE DISEASE_STS_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';

---Null_Test_Case_49---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';

---Null_Test_Case_50---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';

---Null_Test_Case_51---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';

---Null_Test_Case_52---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';

---Null_Test_Case_53---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';

---Null_Test_Case_54---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';

---Null_Test_Case_55---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';

---Null_Test_Case_56---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';

---Null_Test_Case_57---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';

---Null_Test_Case_58---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';

---Null_Test_Case_59---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';

---Null_Test_Case_60---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';

---Null_Test_Case_61---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';

---Null_Test_Case_62---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';

---Null_Test_Case_63---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';

---Null_Test_Case_64---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';

---Null_Test_Case_65---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';

---Null_Test_Case_66---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';

---Null_Test_Case_67---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';

---Null_Test_Case_68---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';

---Null_Test_Case_69---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE DATA_SRC_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';

---Null_Test_Case_70---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_MSR_TYPE_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';

---Null_Test_Case_71---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE MEDCL_HIST_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';

---Null_Test_Case_72---
SEL * FROM GPROD1T_BASE.INDIV_MEDCL_MSR WHERE INDIV_PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';

---Null_Test_Case_73---
SEL * FROM GPROD1T_BASE.DEMOG WHERE DEMOG_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';

---Null_Test_Case_74---
SEL * FROM GPROD1T_BASE.PRTY_DEMOG WHERE PRTY_ID IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';

---Null_Test_Case_75---
SEL * FROM GPROD1T_BASE.PRTY_DEMOG WHERE DEMOG_CD IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';

---Null_Test_Case_76---
SEL * FROM GPROD1T_BASE.PRTY_DEMOG WHERE PRTY_DEMOG_STRT_DT IS NULL AND PROCESS_NAME='TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';

