delete from GPROD1t_GCFR.ETL_PROCESS where SOURCE_NAME = 'VIRUS_C';

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS', 'PRTY', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS', 'ORG', 'UPSERTDELETE', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS', 'ORG_NAME', 'UPSERTDELETE', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY', 'LOCTR', 'UPSERTDELETE', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY', 'GEOGRCL_AREA', 'UPSERTDELETE', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY', 'GEOGRCL_AREA_RLTD', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY', 'PRTY_LOCTR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS', 'PRTY', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS', 'INDIV_NAME', 'UPSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER', 'LOCTR', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER', 'ADDR', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER', 'TLPHN_NUM', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER', 'PRTY_LOCTR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM', 'PRTY_RLTD', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG', 'INDIV_DISEASE_STS', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG', 'INDIV_DISEASE_STS', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT', 'INDIV_DISEASE_STS', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT', 'INDIV_MEDCL_MSR', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG', 'DEMOG', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'TXF', 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG', 'PRTY_DEMOG', 'HISTORY', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_17_VIRUS_C_CITY_SK_CITY_ID_24', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_17_VIRUS_C_GOVERNORATE_SK_GOVERNORATE_CSO_CODE_4', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_1_VIRUS_C_TEAMS_SK_TEAM_ID_53', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_17_VIRUS_C_TEAMS_SK_CITY_ID_24', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_1_VIRUS_C_PERSON_DETAILS_SK_NATIONAL_ID_1', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_17_VIRUS_C_PERSON_DETAILS_SK_MOBILE_NUMBER_2', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_1_VIRUS_C_PERSON_DETAILS_SK_TEAM_ID_53', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_43_VIRUS_C_PERSON_DETAILS_SK_DIABETIC_FLAG_1', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_43_VIRUS_C_PERSON_DETAILS_SK_HYPERTENSIVE_FLAG_1', '', 'INSERT', NULL);

insert into GPROD1t_GCFR.ETL_PROCESS(SOURCE_NAME, PROCESS_TYPE, PROCESS_NAME, BASE_TABLE, APPLY_TYPE, RECORD_ID)
VALUES ('VIRUS_C', 'BKEY', 'BK_43_VIRUS_C_PERSON_DETAILS_SK_SCAN_RESULT_1', '', 'INSERT', NULL);

