delete from GPROD1t_GCFR.SOURCE_TABLES_LKP where SOURCE_NAME = 'VIRUS_C';

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_CITY');

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_GOVERNORATE');

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_TEAMS');

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_PERSON_DETAILS');

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_REJECTION');

insert into GPROD1t_GCFR.SOURCE_TABLES_LKP(SOURCE_NAME, TABLE_NAME)
VALUES ('VIRUS_C', 'VIRUS_C_REJECTION_RULES');

