 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_RLTD','L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_STRT_DTTM','GEOGRCL_AREA_END_DTTM',null,'GEOGRCL_AREA_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_RLTD','L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_STRT_DTTM','GEOGRCL_AREA_END_DTTM',null,'GEOGRCL_AREA_RLTD_ROLE_ID'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_RLTD','L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY','GEOGRCL_AREA_STRT_DTTM','GEOGRCL_AREA_END_DTTM','RLTD_GEOGRCL_AREA_ID',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM',null,'PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM',null,'PRTY_LOCTR_USGE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM','LOCTR_ID',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM',null,'PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM',null,'PRTY_LOCTR_USGE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR','L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER','PRTY_LOCTR_STRT_DTTM','PRTY_LOCTR_END_DTTM','LOCTR_ID',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DISEASE_REGISTRY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'INDIV_PRTY_ID'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT','DISEASE_STS_TYPE_CD',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DISEASE_REGISTRY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'INDIV_PRTY_ID'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT','DISEASE_STS_TYPE_CD',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'DISEASE_REGISTRY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT',null,'INDIV_PRTY_ID'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','INDIV_DISEASE_STS','L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT','DISEASE_STS_STRT_DT','DISEASE_STS_END_DT','DISEASE_STS_TYPE_CD',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'DATA_SRC_TYPE_CD'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'INDIV_PRTY_ID'); 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT',null,'MEDCL_MSR_TYPE_CD'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','INDIV_MEDCL_MSR','L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT','MEDCL_HIST_DT','MEDCL_HIST_END_DT','MEDCL_MSR_VAL',null); 

 
 DELETE FROM GPROD1t_GCFR.HISTORY WHERE PROCESS_NAME = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG';
--History_keys 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','PRTY_DEMOG','L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','PRTY_DEMOG_STRT_DT','PRTY_DEMOG_END_DT',null,'PRTY_ID'); 
--History_columns 
INSERT INTO GPROD1t_GCFR.HISTORY( TRF_TABLE_NAME,PROCESS_NAME,TABLE_NAME,RECORD_ID,START_DATE_COLUMN,END_DATE_COLUMN,HISTORY_COLUMN, HISTORY_KEY)
VALUES ('TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','PRTY_DEMOG','L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG','PRTY_DEMOG_STRT_DT','PRTY_DEMOG_END_DT','DEMOG_CD',null); 

 
