REPLACE VIEW GPROD1V_stg_online.VIRUS_C_CITY AS LOCK ROW FOR ACCESS 
SELECT
 "CITY_ID"
,"CITY_NAME"
,"GOVERNORATE_ID"
,"LOAD_ID"
,"IS_TRANSFERRED"
,"MODIFICATION_TYPE"
,"BATCH_ID"
,"DATA_EXTRACTION_DATE"
,"REF_KEY"
from stg_online.VIRUS_C_CITY t ;

REPLACE VIEW GPROD1V_stg_online.VIRUS_C_GOVERNORATE AS LOCK ROW FOR ACCESS 
SELECT
 "GOVERNORATE_ID"
,"GOVERNORATE_NAME"
,"GOVERNORATE_CSO_CODE"
,"LOAD_ID"
,"IS_TRANSFERRED"
,"MODIFICATION_TYPE"
,"BATCH_ID"
,"DATA_EXTRACTION_DATE"
,"REF_KEY"
from stg_online.VIRUS_C_GOVERNORATE t ;

REPLACE VIEW GPROD1V_stg_online.VIRUS_C_TEAMS AS LOCK ROW FOR ACCESS 
SELECT
 "TEAM_ID"
,"TEAM_NAME"
,"CITY_ID"
,"LOAD_ID"
,"IS_TRANSFERRED"
,"MODIFICATION_TYPE"
,"BATCH_ID"
,"DATA_EXTRACTION_DATE"
,"REF_KEY"
from stg_online.VIRUS_C_TEAMS t ;

REPLACE VIEW GPROD1V_stg_online.VIRUS_C_PERSON_DETAILS AS LOCK ROW FOR ACCESS 
SELECT
 "NATIONAL_ID"
,"NAME"
,"MOBILE_NUMBER"
,"ENTRY_DATE_TIME"
,"TEAM_ID"
,"LOW_PRESSURE"
,"HIGH_PRESSURE"
,"BODY_MASS_INDICATOR"
,"BODY_DIABETES_RESULT"
,"SCAN_RESULT"
,"DIABETIC_FLAG"
,"HYPERTENSIVE_FLAG"
,"HEIGHT"
,"WEIGHT"
,"MESSAGE"
,"HEALTH_INSURANCE_FLAG"
,"BATCH_ID"
,"LOAD_ID"
,"IS_TRANSFERRED"
,"MODIFICATION_TYPE"
,"DATA_EXTRACTION_DATE"
,"REF_KEY"
from stg_online.VIRUS_C_PERSON_DETAILS t ;

REPLACE VIEW GPROD1V_stg_online.VIRUS_C_REJECTION AS LOCK ROW FOR ACCESS 
SELECT
 "REF_KEY"
,"TABLE_ID"
,"RULE_ID"
,"SOURCE_BATCH_ID"
from stg_online.VIRUS_C_REJECTION t ;

REPLACE VIEW GPROD1V_stg_online.VIRUS_C_REJECTION_RULES AS LOCK ROW FOR ACCESS 
SELECT
 "RULE_ID"
,"RULE_DESC"
,"DEVELOPED_BY"
,"ACTIVE"
from stg_online.VIRUS_C_REJECTION_RULES t ;

