create multiset table GPROD1T_STG.VIRUS_C_CITY, Fallback
(
 CITY_ID BIGINT not null 
,CITY_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,GOVERNORATE_ID INTEGER not null 
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,IS_TRANSFERRED INTEGER not null 
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,BATCH_ID INTEGER not null 
,DATA_EXTRACTION_DATE TIMESTAMP(6) not null 
,REF_KEY BIGINT not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (CITY_ID);

create multiset table GPROD1T_WRK.VIRUS_C_CITY, Fallback
(
 CITY_ID BIGINT
,CITY_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC 
,GOVERNORATE_ID INTEGER
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC 
,IS_TRANSFERRED INTEGER
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC 
,BATCH_ID INTEGER
,DATA_EXTRACTION_DATE TIMESTAMP(6)
,REF_KEY BIGINT
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (CITY_ID);

create multiset table GPROD1T_STG.VIRUS_C_GOVERNORATE, Fallback
(
 GOVERNORATE_ID INTEGER not null 
,GOVERNORATE_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,GOVERNORATE_CSO_CODE INTEGER 
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,IS_TRANSFERRED INTEGER not null 
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,BATCH_ID INTEGER not null 
,DATA_EXTRACTION_DATE TIMESTAMP(6) not null 
,REF_KEY BIGINT not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (GOVERNORATE_ID);

create multiset table GPROD1T_WRK.VIRUS_C_GOVERNORATE, Fallback
(
 GOVERNORATE_ID INTEGER
,GOVERNORATE_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC 
,GOVERNORATE_CSO_CODE INTEGER
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC 
,IS_TRANSFERRED INTEGER
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC 
,BATCH_ID INTEGER
,DATA_EXTRACTION_DATE TIMESTAMP(6)
,REF_KEY BIGINT
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (GOVERNORATE_ID);

create multiset table GPROD1T_STG.VIRUS_C_TEAMS, Fallback
(
 TEAM_ID INTEGER not null 
,TEAM_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,CITY_ID INTEGER not null 
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,IS_TRANSFERRED INTEGER not null 
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,BATCH_ID INTEGER not null 
,DATA_EXTRACTION_DATE TIMESTAMP(6) not null 
,REF_KEY BIGINT not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (TEAM_ID);

create multiset table GPROD1T_WRK.VIRUS_C_TEAMS, Fallback
(
 TEAM_ID INTEGER
,TEAM_NAME VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC 
,CITY_ID INTEGER
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC 
,IS_TRANSFERRED INTEGER
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC 
,BATCH_ID INTEGER
,DATA_EXTRACTION_DATE TIMESTAMP(6)
,REF_KEY BIGINT
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (TEAM_ID);

create multiset table GPROD1T_STG.VIRUS_C_PERSON_DETAILS, Fallback
(
 NATIONAL_ID BIGINT not null 
,NAME VARCHAR(350) CHARACTER SET UNICODE NOT CASESPECIFIC  
,MOBILE_NUMBER varchar(50) CHARACTER SET UNICODE NOT CASESPECIFIC  
,ENTRY_DATE_TIME TIMESTAMP(6) 
,TEAM_ID INTEGER 
,LOW_PRESSURE INTEGER 
,HIGH_PRESSURE INTEGER 
,BODY_MASS_INDICATOR DECIMAL(8,2) 
,BODY_DIABETES_RESULT INTEGER 
,SCAN_RESULT INTEGER 
,DIABETIC_FLAG INTEGER 
,HYPERTENSIVE_FLAG INTEGER 
,HEIGHT DECIMAL(18,2) 
,WEIGHT DECIMAL(18,2) 
,MESSAGE VARCHAR(350) CHARACTER SET UNICODE NOT CASESPECIFIC  
,HEALTH_INSURANCE_FLAG INTEGER not null 
,BATCH_ID INTEGER not null 
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,IS_TRANSFERRED INTEGER not null 
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,DATA_EXTRACTION_DATE TIMESTAMP(6) not null 
,REF_KEY BIGINT not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (NATIONAL_ID);

create multiset table GPROD1T_WRK.VIRUS_C_PERSON_DETAILS, Fallback
(
 NATIONAL_ID BIGINT
,NAME VARCHAR(350) CHARACTER SET UNICODE NOT CASESPECIFIC 
,MOBILE_NUMBER varchar(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
,ENTRY_DATE_TIME TIMESTAMP(6)
,TEAM_ID INTEGER
,LOW_PRESSURE INTEGER
,HIGH_PRESSURE INTEGER
,BODY_MASS_INDICATOR DECIMAL(8,2)
,BODY_DIABETES_RESULT INTEGER
,SCAN_RESULT INTEGER
,DIABETIC_FLAG INTEGER
,HYPERTENSIVE_FLAG INTEGER
,HEIGHT DECIMAL(18,2)
,WEIGHT DECIMAL(18,2)
,MESSAGE VARCHAR(350) CHARACTER SET UNICODE NOT CASESPECIFIC 
,HEALTH_INSURANCE_FLAG INTEGER
,BATCH_ID INTEGER
,LOAD_ID VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC 
,IS_TRANSFERRED INTEGER
,MODIFICATION_TYPE char(1) CHARACTER SET UNICODE NOT CASESPECIFIC 
,DATA_EXTRACTION_DATE TIMESTAMP(6)
,REF_KEY BIGINT
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (NATIONAL_ID);

create multiset table GPROD1T_STG.VIRUS_C_REJECTION, Fallback
(
 REF_KEY BIGINT not null 
,TABLE_ID INTEGER not null 
,RULE_ID INTEGER not null 
,SOURCE_BATCH_ID INTEGER not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (RULE_ID);

create multiset table GPROD1T_WRK.VIRUS_C_REJECTION, Fallback
(
 REF_KEY BIGINT
,TABLE_ID INTEGER
,RULE_ID INTEGER
,SOURCE_BATCH_ID INTEGER
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (RULE_ID);

create multiset table GPROD1T_STG.VIRUS_C_REJECTION_RULES, Fallback
(
 RULE_ID INTEGER not null 
,RULE_DESC varchar(100) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,DEVELOPED_BY varchar(20) CHARACTER SET UNICODE NOT CASESPECIFIC  not null 
,ACTIVE INTEGER not null 
,INS_DTTM  TIMESTAMP(6) NOT NULL 
)Primary Index (RULE_ID);

create multiset table GPROD1T_WRK.VIRUS_C_REJECTION_RULES, Fallback
(
 RULE_ID INTEGER
,RULE_DESC varchar(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
,DEVELOPED_BY varchar(20) CHARACTER SET UNICODE NOT CASESPECIFIC 
,ACTIVE INTEGER
,INS_DTTM  TIMESTAMP(6) NOT NULL 
,REJECTED INTEGER
,BATCH_LOADED INTEGER
,NEW_ROW INTEGER
)Primary Index (RULE_ID);

