EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(17, 'LOCTR', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(17, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 17, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(17, 24, 'LOCTR_VIRUS_C_CITY');

EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(17, 'LOCTR', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(17, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 17, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(17, 4, 'LOCTR_ID_004');

EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(1, 'PRTY', 'BKEY_1_PRTY', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_1_PRTY', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(1, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_1_PRTY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_1_PRTY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_1_PRTY', 1, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(1, 53, 'PRTY_VIRUS_C_TEAM');

EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(1, 'PRTY', 'BKEY_1_PRTY', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_1_PRTY', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(1, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_1_PRTY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_1_PRTY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_1_PRTY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_1_PRTY', 1, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(1, 1, 'PRTY_ID_001');

EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(17, 'LOCTR', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(17, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_17_LOCTR', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_17_LOCTR', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_17_LOCTR', 17, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(17, 2, 'LOCTR_ID_002');

EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Key_Set(43, 'DISEASE_REGISTRY', 'BKEY_43_DISEASE_REGISTRY', 'GPROD1V_UTLFW');
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CT('GPROD1T_UTLFW', 'BKEY_43_DISEASE_REGISTRY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_CV('GPROD1T_UTLFW', 'BKEY_43_DISEASE_REGISTRY', 'GPROD1V_UTLFW', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_Key_Set_RI_Check(43, :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CT('BKEY_43_DISEASE_REGISTRY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_St_Key_NextId_CV('BKEY_43_DISEASE_REGISTRY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CT('BKEY_43_DISEASE_REGISTRY', '1', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEY_S_K_NextId_Log_CV('BKEY_43_DISEASE_REGISTRY', :OMessage);
CALL GPROD1P_UT.GCFR_UT_BKEYStandKeyNextId_Gen('GPROD1T_UTLFW', 'BKEY_43_DISEASE_REGISTRY', 43, :OMessage);
EXEC GPROD1M_GCFR.GCFR_Register_Bkey_Domain(43, 1, 'HTC_DISEASE_ICD10');

