REPLACE VIEW GPROD1V_SRCI.VIRUS_C_CITY AS LOCK ROW FOR ACCESS
SELECT 
 TRIM(Trailing '.' from TRIM(t.CITY_ID)) CITY_ID
,t.CITY_NAME
,t.GOVERNORATE_ID
,t.LOAD_ID
,t.IS_TRANSFERRED
,t.MODIFICATION_TYPE
,t.BATCH_ID
,t.DATA_EXTRACTION_DATE
,t.REF_KEY
,( Select  bk1.EDW_Key
	From GPROD1V_UTLFW.BKEY_17_LOCTR bk1
	Where  bk1.Source_Key = TRIM(Trailing '.' from TRIM(CITY_ID))
	and  bk1.Domain_ID = 24) AS SK_CITY_ID
FROM GPROD1V_STG.VIRUS_C_CITY t;

REPLACE VIEW GPROD1V_SRCI.VIRUS_C_GOVERNORATE AS LOCK ROW FOR ACCESS
SELECT 
 t.GOVERNORATE_ID
,t.GOVERNORATE_NAME
,TRIM(Trailing '.' from TRIM(t.GOVERNORATE_CSO_CODE)) GOVERNORATE_CSO_CODE
,t.LOAD_ID
,t.IS_TRANSFERRED
,t.MODIFICATION_TYPE
,t.BATCH_ID
,t.DATA_EXTRACTION_DATE
,t.REF_KEY
,( Select  bk1.EDW_Key
	From GPROD1V_UTLFW.BKEY_17_LOCTR bk1
	Where  bk1.Source_Key = TRIM(Trailing '.' from TRIM(GOVERNORATE_CSO_CODE))
	and  bk1.Domain_ID = 4) AS SK_GOVERNORATE_CSO_CODE
FROM GPROD1V_STG.VIRUS_C_GOVERNORATE t;

REPLACE VIEW GPROD1V_SRCI.VIRUS_C_TEAMS AS LOCK ROW FOR ACCESS
SELECT 
 TRIM(Trailing '.' from TRIM(t.TEAM_ID)) TEAM_ID
,t.TEAM_NAME
,TRIM(Trailing '.' from TRIM(t.CITY_ID)) CITY_ID
,t.LOAD_ID
,t.IS_TRANSFERRED
,t.MODIFICATION_TYPE
,t.BATCH_ID
,t.DATA_EXTRACTION_DATE
,t.REF_KEY
,( Select  bk1.EDW_Key
	From GPROD1V_UTLFW.BKEY_1_PRTY bk1
	Where  bk1.Source_Key = TRIM(Trailing '.' from TRIM(TEAM_ID))
	and  bk1.Domain_ID = 53) AS SK_TEAM_ID
,( Select  bk2.EDW_Key
	From GPROD1V_UTLFW.BKEY_17_LOCTR bk2
	Where  bk2.Source_Key = TRIM(Trailing '.' from TRIM(CITY_ID))
	and  bk2.Domain_ID = 24) AS SK_CITY_ID
FROM GPROD1V_STG.VIRUS_C_TEAMS t;

REPLACE VIEW GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS AS LOCK ROW FOR ACCESS
SELECT 
 TRIM(Trailing '.' from TRIM(t.NATIONAL_ID)) NATIONAL_ID
,t.NAME
,TRIM(Trailing '.' from TRIM(t.MOBILE_NUMBER)) MOBILE_NUMBER
,t.ENTRY_DATE_TIME
,TRIM(Trailing '.' from TRIM(t.TEAM_ID)) TEAM_ID
,t.LOW_PRESSURE
,t.HIGH_PRESSURE
,t.BODY_MASS_INDICATOR
,t.BODY_DIABETES_RESULT
,t.SCAN_RESULT
,t.DIABETIC_FLAG
,t.HYPERTENSIVE_FLAG
,t.HEIGHT
,t.WEIGHT
,t.MESSAGE
,t.HEALTH_INSURANCE_FLAG
,t.BATCH_ID
,t.LOAD_ID
,t.IS_TRANSFERRED
,t.MODIFICATION_TYPE
,t.DATA_EXTRACTION_DATE
,t.REF_KEY
,( Select  bk1.EDW_Key
	From GPROD1V_UTLFW.BKEY_1_PRTY bk1
	Where  bk1.Source_Key = TRIM(Trailing '.' from TRIM(NATIONAL_ID))
	and  bk1.Domain_ID = 1) AS SK_NATIONAL_ID
,( Select  bk2.EDW_Key
	From GPROD1V_UTLFW.BKEY_17_LOCTR bk2
	Where  bk2.Source_Key = TRIM(Trailing '.' from TRIM(MOBILE_NUMBER))
	and  bk2.Domain_ID = 2) AS SK_MOBILE_NUMBER
,( Select  bk3.EDW_Key
	From GPROD1V_UTLFW.BKEY_1_PRTY bk3
	Where  bk3.Source_Key = TRIM(Trailing '.' from TRIM(TEAM_ID))
	and  bk3.Domain_ID = 53) AS SK_TEAM_ID
,( Select  bk4.EDW_Key
	From GPROD1V_UTLFW.BKEY_43_DISEASE_REGISTRY bk4
	Where  bk4.Source_Key = TRIM(Trailing '.' from TRIM(E11.0'))
	and  bk4.Domain_ID = 1) AS SK_DIABETIC_FLAG
,( Select  bk5.EDW_Key
	From GPROD1V_UTLFW.BKEY_43_DISEASE_REGISTRY bk5
	Where  bk5.Source_Key = TRIM(Trailing '.' from TRIM('I10'))
	and  bk5.Domain_ID = 1) AS SK_HYPERTENSIVE_FLAG
,( Select  bk6.EDW_Key
	From GPROD1V_UTLFW.BKEY_43_DISEASE_REGISTRY bk6
	Where  bk6.Source_Key = TRIM(Trailing '.' from TRIM('B18.2'))
	and  bk6.Domain_ID = 1) AS SK_SCAN_RESULT
FROM GPROD1V_STG.VIRUS_C_PERSON_DETAILS t;

REPLACE VIEW GPROD1V_SRCI.VIRUS_C_REJECTION AS LOCK ROW FOR ACCESS
SELECT 
 t.REF_KEY
,t.TABLE_ID
,t.RULE_ID
,t.SOURCE_BATCH_ID
FROM GPROD1V_STG.VIRUS_C_REJECTION t;

REPLACE VIEW GPROD1V_SRCI.VIRUS_C_REJECTION_RULES AS LOCK ROW FOR ACCESS
SELECT 
 t.RULE_ID
,t.RULE_DESC
,t.DEVELOPED_BY
,t.ACTIVE
FROM GPROD1V_STG.VIRUS_C_REJECTION_RULES t;

