CREATE SET TABLE GPROD1T_BASE.PRTY, FALLBACK (
PRTY_ID INTEGER NOT NULL 
 ,PRTY_SBTYPE_CD INTEGER 
 ,PRTY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,PRTY_STRT_DTTM TIMESTAMP(0) 
 ,PRTY_END_DTTM TIMESTAMP(0) 
 ,INIT_DATA_SRC_CD INTEGER 
 ,PRTY_TYPE_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (PRTY_ID); 
  
CREATE SET TABLE GPROD1T_BASE.ORG, FALLBACK (
ORG_PRTY_ID INTEGER NOT NULL 
 ,PARNT_ORG_PRTY_ID INTEGER 
 ,ORG_SBTYPE_CD INTEGER 
 ,LEGL_CLASFCN_CD INTEGER 
 ,OWNRSHP_TYPE_CD INTEGER 
 ,ORG_ESTBLD_DTTM TIMESTAMP(0) 
 ,DATA_SRC_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (ORG_PRTY_ID); 
  
CREATE SET TABLE GPROD1T_BASE.ORG_NAME, FALLBACK (
ORG_PRTY_ID INTEGER NOT NULL 
 ,NAME_TYPE_CD INTEGER NOT NULL 
 ,ORG_NAME_STRT_DT TIMESTAMP(0) NOT NULL 
 ,ORG_NAME_END_DT TIMESTAMP(0) 
 ,ORG_NAME VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,ORG_NAME_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,DATA_SRC_CD INTEGER NOT NULL 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (ORG_PRTY_ID,NAME_TYPE_CD,ORG_NAME_STRT_DT,DATA_SRC_CD); 
  
CREATE SET TABLE GPROD1T_BASE.LOCTR, FALLBACK (
LOCTR_ID INTEGER NOT NULL 
 ,LOCTR_SBTYPE_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (LOCTR_ID); 
  
CREATE SET TABLE GPROD1T_BASE.GEOGRCL_AREA, FALLBACK (
GEOGRCL_AREA_ID INTEGER NOT NULL 
 ,GEOGRCL_AREA_SBTYPE_CD INTEGER 
 ,GEOGRCL_AREA_SHRT_NAME VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,GEOGRCL_AREA_NAME VARCHAR(2000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,GEOGRCL_AREA_DESC VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (GEOGRCL_AREA_ID); 
  
CREATE SET TABLE GPROD1T_BASE.GEOGRCL_AREA_RLTD, FALLBACK (
GEOGRCL_AREA_ID INTEGER NOT NULL 
 ,RLTD_GEOGRCL_AREA_ID INTEGER NOT NULL 
 ,GEOGRCL_AREA_STRT_DTTM TIMESTAMP(0) NOT NULL 
 ,GEOGRCL_AREA_END_DTTM TIMESTAMP(0) 
 ,GEOGRCL_AREA_RLTD_ROLE_ID INTEGER NOT NULL 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_STRT_DTTM,GEOGRCL_AREA_RLTD_ROLE_ID); 
  
CREATE SET TABLE GPROD1T_BASE.PRTY_LOCTR, FALLBACK (
PRTY_ID INTEGER NOT NULL 
 ,LOCTR_ID INTEGER NOT NULL 
 ,PRTY_LOCTR_STRT_DTTM TIMESTAMP(0) NOT NULL 
 ,PRTY_LOCTR_USGE_CD INTEGER NOT NULL 
 ,PRTY_LOCTR_END_DTTM TIMESTAMP(0) 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (PRTY_ID,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,PRTY_LOCTR_USGE_CD); 
  
CREATE SET TABLE GPROD1T_BASE.INDIV_NAME, FALLBACK (
INDIV_PRTY_ID INTEGER NOT NULL 
 ,NAME_TYPE_CD INTEGER NOT NULL 
 ,INDIV_NAME_STRT_DT TIMESTAMP(0) NOT NULL 
 ,INDIV_NAME_END_DT TIMESTAMP(0) 
 ,GVN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,MDL_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,FMLY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,NAME_PREFIX_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,NAME_SFX_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,DATA_SRC_CD INTEGER NOT NULL 
 ,FULL_NAME VARCHAR(2000) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (INDIV_PRTY_ID,NAME_TYPE_CD,INDIV_NAME_STRT_DT,DATA_SRC_CD); 
  
CREATE SET TABLE GPROD1T_BASE.ADDR, FALLBACK (
ADDR_ID INTEGER NOT NULL 
 ,ADDR_SBTYPE_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (ADDR_ID); 
  
CREATE SET TABLE GPROD1T_BASE.TLPHN_NUM, FALLBACK (
TLPHN_NUM_ID INTEGER NOT NULL 
 ,TLPHN_NUM VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,TLPHN_CTRY_CD_NUM VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,TLPHN_AREA_CD_NUM VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,TLPHN_EXCH_NUM VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,TLPHN_LN_NUM VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,TLPHN_EXTN_NUM VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (TLPHN_NUM_ID); 
  
CREATE SET TABLE GPROD1T_BASE.PRTY_RLTD, FALLBACK (
PRTY_ID INTEGER NOT NULL 
 ,RLTD_PRTY_ID INTEGER NOT NULL 
 ,RLTD_ROLE_CD INTEGER NOT NULL 
 ,PRTY_RLTD_STRT_DTTM TIMESTAMP(0) NOT NULL 
 ,PRTY_RLTD_END_DTTM TIMESTAMP(0) 
 ,RLTD_STS_RSN_CD INTEGER 
 ,RLTD_STS_TYPE_CD INTEGER 
 ,PRTY_STRC_TYPE_CD INTEGER 
 ,DATA_SRC_CD INTEGER NOT NULL 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (PRTY_ID,RLTD_PRTY_ID,RLTD_ROLE_CD,PRTY_RLTD_STRT_DTTM,DATA_SRC_CD); 
  
CREATE SET TABLE GPROD1T_BASE.INDIV_DISEASE_STS, FALLBACK (
DISEASE_STS_STRT_DT DATE NOT NULL 
 ,DISEASE_STS_END_DT DATE 
 ,INDIV_PRTY_ID INTEGER NOT NULL 
 ,DISEASE_REGISTRY_ID INTEGER NOT NULL 
 ,DATA_SRC_TYPE_CD INTEGER NOT NULL 
 ,DISEASE_STS_TYPE_CD INTEGER NOT NULL 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (DISEASE_STS_STRT_DT,INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD); 
  
CREATE SET TABLE GPROD1T_BASE.INDIV_MEDCL_MSR, FALLBACK (
DATA_SRC_TYPE_CD INTEGER NOT NULL 
 ,MEDCL_MSR_TYPE_CD INTEGER NOT NULL 
 ,MEDCL_HIST_DT DATE NOT NULL 
 ,MEDCL_HIST_END_DT DATE 
 ,MEDCL_MSR_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,INDIV_PRTY_ID INTEGER NOT NULL 
 ,MEDCL_MSR_UOM_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,MEDCL_HIST_DT,INDIV_PRTY_ID); 
  
CREATE SET TABLE GPROD1T_BASE.DEMOG, FALLBACK (
DEMOG_CD INTEGER NOT NULL 
 ,DEMOG_GRP_CD INTEGER 
 ,DEMOG_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,DEMOG_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,SRC_ORG_PRTY_ID INTEGER 
 ,DATA_SRC_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (DEMOG_CD); 
  
CREATE SET TABLE GPROD1T_BASE.PRTY_DEMOG, FALLBACK (
PRTY_ID INTEGER NOT NULL 
 ,DEMOG_CD INTEGER NOT NULL 
 ,PRTY_DEMOG_STRT_DT DATE NOT NULL 
 ,PRTY_DEMOG_END_DT DATE 
 ,DEMOG_VAL_CD INTEGER 
 ,DEMOG_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
 ,DATA_SRC_CD INTEGER 
 ,Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 
) UNIQUE PRIMARY INDEX (PRTY_ID,DEMOG_CD,PRTY_DEMOG_STRT_DT); 
  
