CREATE SET TABLE GPROD1T_BASE.ACCS_METH_ROLE, FALLBACK (
ACCS_METH_ROLE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
ACCS_METH_ROLE_CD INTEGER NOT NULL ,
ACCS_METH_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCS_METH_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCS_METH_TYPE, FALLBACK (
ACCS_METH_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ACCS_METH_TYPE_CD INTEGER NOT NULL ,
ACCS_METH_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCS_METH_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_ADDR_STS_TYPE, FALLBACK (
ACCT_ADDR_STS_DESC VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ACCT_ADDR_STS_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_ADDR_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_PRPS_SBTYPE, FALLBACK (
ACCT_PRPS_SBTYPE_CD INTEGER NOT NULL ,
ACCT_PRPS_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_PRPS_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_RLTD_RSN, FALLBACK (
ACCT_RLTD_RSN_CD INTEGER NOT NULL ,
ACCT_RLTD_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_RLTD_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_STS_TYPE, FALLBACK (
ACCT_STS_CD INTEGER NOT NULL ,
ACCT_STS_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ACCT_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_TYPE, FALLBACK (
ACCT_TYPE_CD INTEGER NOT NULL ,
ACCT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ACCT_ROLE, FALLBACK (
PRTY_ACCT_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRTY_ACCT_ROLE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ACCT_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.ADDR_SBTYPE, FALLBACK (
ADDR_SBTYPE_CD INTEGER NOT NULL ,
ADDR_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ADDR_SBTYPE_CD); 

--Error: Table ADDR_USGE_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.ADDR_USGE_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.AGMT_TYPE, FALLBACK (
AGMT_TYPE_CD INTEGER NOT NULL ,
AGMT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSET_ROLE_TYPE, FALLBACK (
ASSET_ROLE_CD INTEGER NOT NULL ,
ASSET_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSET_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSOC_EXP_CTGY, FALLBACK (
ASSOC_EXPENDR_CTGY_CD INTEGER NOT NULL ,
ASSOC_EXPENDR_CTGY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ASSOC_EXPENDR_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSOC_EXPENDR_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.SALRY_WG_TYPE, FALLBACK (
SALRY_WG_TYPE_CD INTEGER NOT NULL ,
SALRY_WG_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SALRY_WG_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSOC_LOC_ROLE, FALLBACK (
ASSOC_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ASSOC_ROLE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSOC_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.BILG_CYCL, FALLBACK (
BILG_CYCL_ID INTEGER NOT NULL ,
BILG_CYCL_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
BILG_CYCL_FRQCY_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (BILG_CYCL_ID); 

CREATE SET TABLE GPROD1T_BASE.BILG_TYPE, FALLBACK (
BILG_TYPE_CD INTEGER NOT NULL ,
BILG_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
BILG_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (BILG_TYPE_CD); 

--Error: Table CR_STS Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.CR_STS, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.CRTFTN_GRP, FALLBACK (
CRTFTN_GRP_CD INTEGER NOT NULL ,
CRTFTN_GRP_DESC VARCHAR(500) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CRTFTN_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.DATA_SRC_TYPE, FALLBACK (
DATA_SRC_CD INTEGER NOT NULL ,
DATA_SRC_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DATA_SRC_CD); 

CREATE SET TABLE GPROD1T_BASE.DEMOG_GRP, FALLBACK (
DEMOG_GRP_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_GRP_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DEMOG_GRP_CD); 

--Error: Table DOC_RLTD_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.DOC_RLTD_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

--Error: Table DOC_STS_RSN_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.DOC_STS_RSN_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

--Error: Table DOC_STS_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.DOC_STS_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.DOC_TYPE, FALLBACK (
DOC_TYPE_CD INTEGER NOT NULL ,
DOC_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DOC_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DSCPTR_TYPE, FALLBACK (
DSCPTR_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DSCPTR_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DSCPTR_TYPE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DSCPTR_TYPE_CD); 

--Error: Table EQMNT_INST_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.EQMNT_INST_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.FEAT_SBTYPE, FALLBACK (
FEAT_SBTYPE_CD INTEGER NOT NULL ,
FEAT_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (FEAT_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.COST_TYPE, FALLBACK (
COST_TYPE_CD INTEGER NOT NULL ,
COST_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
COST_CTGY_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (COST_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.AGMT_FEAT_TYPE, FALLBACK (
AGMT_FEAT_TYPE_CD INTEGER NOT NULL ,
AGMT_FEAT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_FEAT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.FUNCLTY, FALLBACK (
FUNCLTY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
FUNCLTY_CD INTEGER NOT NULL ,
FUNCLTY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
FUNCLTY_CD INTEGER NOT NULL ,
FUNCLTY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
FUNCLTY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (FUNCLTY_CD,FUNCLTY_CD); 

CREATE SET TABLE GPROD1T_BASE.GEOGRCL_AREA_RLTD_ROLE, FALLBACK (
GEOGRCL_AREA_RLTD_ROLE_ID INTEGER NOT NULL ,
GEOGRCL_AREA_RLTD_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (GEOGRCL_AREA_RLTD_ROLE_ID); 

CREATE SET TABLE GPROD1T_BASE.GEOGRCL_AREA_SBTYPE, FALLBACK (
GEOGRCL_AREA_SBTYPE_CD INTEGER NOT NULL ,
GEOGRCL_AREA_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (GEOGRCL_AREA_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.GNDR, FALLBACK (
GNDR_CD INTEGER NOT NULL ,
GNDR_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (GNDR_CD); 

CREATE SET TABLE GPROD1T_BASE.JOB_CLASFCN, FALLBACK (
JOB_CLASFCN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
JOB_CLASFCN_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (JOB_CLASFCN_CD); 

CREATE SET TABLE GPROD1T_BASE.LEGL_CLASFCN, FALLBACK (
LEGL_CLASFCN_CD INTEGER NOT NULL ,
LEGL_CLASFCN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LEGL_CLASFCN_CD); 

CREATE SET TABLE GPROD1T_BASE.LMT_SBTYPE, FALLBACK (
LMT_SBTYPE_CD INTEGER NOT NULL ,
LMT_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LMT_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.LMT_TYPE, FALLBACK (
LMT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
LMT_TYPE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LMT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.LOC_SBTYPE, FALLBACK (
LOC_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
LOC_SBTYPE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOC_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.LOCTR_SBTYPE, FALLBACK (
LOCTR_SBTYPE_CD INTEGER NOT NULL ,
LOCTR_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOCTR_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.MEDCL_MSR_TYPE, FALLBACK (
MEDCL_MSR_TYPE_CD INTEGER NOT NULL ,
MEDCL_MSR_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (MEDCL_MSR_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.MRTL_STS, FALLBACK (
MRTL_STS_CD INTEGER NOT NULL ,
MRTL_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (MRTL_STS_CD); 

--Error: Table  Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE., FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.NAME_TYPE, FALLBACK (
NAME_TYPE_CD INTEGER NOT NULL ,
NAME_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (NAME_TYPE_CD); 

--Error: Table OFRG_STS_RSN Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.OFRG_STS_RSN, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

--Error: Table OFRG_STS_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.OFRG_STS_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.ORG_HIERY_TYPE, FALLBACK (
ORG_HIERY_TYPE_CD INTEGER NOT NULL ,
ORG_HIERY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ORG_HIERY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ORG_SBTYPE, FALLBACK (
ORG_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
ORG_SBTYPE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ORG_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PAYRL_TSACTN_SBTYPE, FALLBACK (
PAYRL_TSACTN_SBTYPE_CD INTEGER NOT NULL ,
PAYRL_TSACTN_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PAYRL_TSACTN_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PMT_PRTY_ROLE, FALLBACK (
PMT_PRTY_ROLE_CD INTEGER NOT NULL ,
PMT_PRTY_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PMT_PRTY_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PMT_TYPE, FALLBACK (
PMT_TYPE_CD INTEGER NOT NULL ,
PMT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PMT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSET_VAL_TYPE, FALLBACK (
ASSET_VAL_TYPE_CD INTEGER NOT NULL ,
ASSET_VAL_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSET_VAL_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.POSITN_TYPE, FALLBACK (
POSITN_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
POSITN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
POSITN_TYPE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (POSITN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PROD_CLAS_TYPE, FALLBACK (
PROD_CLAS_TYPE_CD INTEGER NOT NULL ,
PROD_CLAS_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PROD_CLAS_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PROD_CLAS_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PROD_GRP, FALLBACK (
PROD_GRP_CD INTEGER NOT NULL ,
PROD_GRP_STRT_DT DATE ,
PROD_GRP_END_DT DATE ,
PROD_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PROD_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.PROD_SBTYPE, FALLBACK (
PROD_SBTYPE_CD INTEGER NOT NULL ,
PROD_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PROD_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PROD_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_ACCT_ROLE, FALLBACK (
PRTY_ASSET_ACCT_ROLE_CD INTEGER NOT NULL ,
PRTY_ASSET_ACCT_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_ACCT_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_LOCTR_ROLE, FALLBACK (
PRTY_ASSET_LOCTR_ROLE_CD INTEGER NOT NULL ,
PRTY_ASSET_LOCTR_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_LOCTR_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_RLTD_TYPE, FALLBACK (
PRTY_ASSET_RLTD_TYPE_CD INTEGER NOT NULL ,
PRTY_ASSET_RLTD_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_RLTD_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_SBTYPE, FALLBACK (
PRTY_ASSET_SBTYPE_CD INTEGER NOT NULL ,
PRTY_ASSET_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_DOC_ROLE, FALLBACK (
PRTY_DOC_ROLE_CD INTEGER NOT NULL ,
PRTY_DOC_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_DOC_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_IDNTFTN_LOCTR_USGE, FALLBACK (
PRTY_IDNTFTN_LOCTR_USGE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRTY_IDNTFTN_LOCTR_USGE_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_IDNTFTN_LOCTR_USGE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_IDNTFTN_TYPE, FALLBACK (
PRTY_IDNTFTN_TYPE_CD INTEGER NOT NULL ,
PRTY_IDNTFTN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRTY_IDNTFTN_CTGY_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_IDNTFTN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_LOCTR_USGE, FALLBACK (
PRTY_LOCTR_USGE_CD INTEGER NOT NULL ,
PRTY_LOCTR_USGE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_LOCTR_USGE_CD); 

--Error: Table PRTY_OFRG_ROLE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.PRTY_OFRG_ROLE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.PRTY_RLTD_ROLE, FALLBACK (
PRTY_RLTD_ROLE_CD INTEGER NOT NULL ,
PRTY_RLTD_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_RLTD_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_RLTD_STS_RSN, FALLBACK (
PRTY_RLTD_STS_RSN_CD INTEGER NOT NULL ,
PRTY_RLTD_STS_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_RLTD_STS_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_SBSCRPN_ROLE, FALLBACK (
PRTY_SBSCRPN_ROLE_CD INTEGER NOT NULL ,
PRTY_SBSCRPN_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_SBSCRPN_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_SBTYPE, FALLBACK (
PRTY_SBTYPE_CD INTEGER NOT NULL ,
PRTY_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_TO_PRTY_ASSET_RSN, FALLBACK (
PRTY_TO_PRTY_ASSET_RSN_ID INTEGER NOT NULL ,
PRTY_TO_PRTY_ASSET_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_TO_PRTY_ASSET_RSN_ID); 

CREATE SET TABLE GPROD1T_BASE.PRTY_TYPE, FALLBACK (
PRTY_TYPE_CD INTEGER NOT NULL ,
PRTY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRTY_TYPE_DESC_ARABIC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.REAL_ESTAT_TYPE, FALLBACK (
REAL_ESTAT_TYPE_CD INTEGER NOT NULL ,
REAL_ESTAT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (REAL_ESTAT_TYPE_CD); 

--Error: Table RLGN Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.RLGN, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.HOUSE_HOLD_RLTNSHP_TYPE, FALLBACK (
HOUSE_HOLD_RLTNSHP_TYPE_CD INTEGER NOT NULL ,
HOUSE_HOLD_RLTNSHP_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (HOUSE_HOLD_RLTNSHP_TYPE_CD); 

--Error: Table SLS_TSACTN_STS Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.SLS_TSACTN_STS, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.UOM, FALLBACK (
UOM_CD INTEGER NOT NULL ,
UOM_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
UOM_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
UOM_CTGY_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (UOM_CD); 

CREATE SET TABLE GPROD1T_BASE.VIST_SBTYPE, FALLBACK (
VIST_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
VIST_SBTYPE_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (VIST_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSOC_SKIL_GRP, FALLBACK (
ASSOC_SKIL_GRP_CD INTEGER NOT NULL ,
ASSOC_SKIL_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSOC_SKIL_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.FEAT, FALLBACK (
FEAT_ID INTEGER NOT NULL ,
FEAT_SBTYPE_CD INTEGER ,
FEATURE_INSURANCE_SUBTYPE_CD INTEGER ,
FEAT_CLASFCN_CD INTEGER ,
FEAT_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
FEAT_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
COMN_FEAT_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
FEAT_LVL_SBTYPE_CNT INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (FEAT_ID); 

CREATE SET TABLE GPROD1T_BASE.FEAT_DOC_TYPE, FALLBACK (
FEAT_DOC_TYPE_CD INTEGER NOT NULL ,
FEAT_DOC_TYPE_DESC VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (FEAT_DOC_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.OCPTN_TYPE, FALLBACK (
OCPTN_TYPE_CD INTEGER NOT NULL ,
OCPTN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (OCPTN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_STS, FALLBACK (
PRTY_STS_CD INTEGER NOT NULL ,
PRTY_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_STS_XREF_TYPE, FALLBACK (
PRTY_STS_XREF_TYPE_CD INTEGER NOT NULL ,
PRTY_STS_XREF_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_STS_XREF_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_BAL_TYPE, FALLBACK (
ACCT_BAL_TYPE_CD INTEGER NOT NULL ,
ACCT_BAL_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_BAL_TYPE_CD); 

--Error: Table ACCT_LOCTR_USGE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.ACCT_LOCTR_USGE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.CHRG_CLAS_CTGY, FALLBACK (
CHRG_CLAS_CTGY_CD INTEGER NOT NULL ,
CHRG_CLAS_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CHRG_CLAS_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.BILG_STMT_CHRG_TYPE, FALLBACK (
BILG_STMT_CHRG_TYPE_CD INTEGER NOT NULL ,
BILG_STMT_CHRG_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (BILG_STMT_CHRG_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DISEASE_STS_TYPE, FALLBACK (
DISEASE_STS_TYPE_CD INTEGER NOT NULL ,
DISEASE_STS_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DISEASE_STS_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.SBSCRPN_HNDST_TYPE, FALLBACK (
SBSCRPN_HNDST_TYPE_CD INTEGER NOT NULL ,
SBSCRPN_HNDST_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SBSCRPN_HNDST_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_LOC_ROLE, FALLBACK (
PRTY_ASSET_LOC_ROLE_CD INTEGER NOT NULL ,
PRTY_ASSET_LOC_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_LOC_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.REAL_ESTAT_DTL_CTGY_TYPE, FALLBACK (
REAL_ESTAT_DTL_CTGY_TYPE_CD INTEGER NOT NULL ,
REAL_ESTAT_DTL_CTGY_TYPE_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (REAL_ESTAT_DTL_CTGY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ACCT_RSN_TYPE, FALLBACK (
PRTY_ACCT_RSN_CD INTEGER NOT NULL ,
PRTY_ACCT_RSN_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ACCT_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.TRAT, FALLBACK (
TRAT_CD INTEGER NOT NULL ,
TRAT_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
TRAT_TYPE_CD INTEGER NOT NULL ,
TRAT_UOM_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (TRAT_CD); 

CREATE SET TABLE GPROD1T_BASE.LOC_PRTY_ROLE, FALLBACK (
LOC_PRTY_ROLE_CD INTEGER NOT NULL ,
LOC_PRTY_ROLE_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOC_PRTY_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.LOC_ID_TYPE, FALLBACK (
LOC_ID_TYPE_CD INTEGER NOT NULL ,
LOC_ID_TYPE_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOC_ID_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.LOC_TYPE, FALLBACK (
LOC_TYPE_CD INTEGER NOT NULL ,
LOC_TYPE_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOC_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DEMOG, FALLBACK (
DEMOG_CD INTEGER NOT NULL ,
DEMOG_GRP_CD INTEGER ,
DEMOG_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
SRC_ORG_PRTY_ID INTEGER ,
DATA_SRC_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DEMOG_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSOC_EMPLMT_GRP, FALLBACK (
ASSOC_EMPLMT_GRP_CD INTEGER NOT NULL ,
ASSOC_EMPLMT_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSOC_EMPLMT_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.TRAT_TYPE, FALLBACK (
TRAT_TYPE_CD INTEGER NOT NULL ,
TRAT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (TRAT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.SITE_SBTYPE, FALLBACK (
SITE_SBTYPE_CD INTEGER NOT NULL ,
SITE_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SITE_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.SITE_STS_TYPE, FALLBACK (
SITE_STS_TYPE_CD INTEGER NOT NULL ,
SITE_STS_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SITE_STS_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DSABLY_TYPE, FALLBACK (
DSABLY_TYPE_CD INTEGER NOT NULL ,
DSABLY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DSABLY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DSABLY_RSN_TYPE, FALLBACK (
DSABLY_RSN_TYPE_CD INTEGER NOT NULL ,
DSABLY_RSN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DSABLY_RSN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.QSTR_CTGY, FALLBACK (
QSTR_CTGY_CD INTEGER NOT NULL ,
QSTR_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (QSTR_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_PRTY_ROLE, FALLBACK (
EV_PRTY_ROLE_CD INTEGER NOT NULL ,
EV_PRTY_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_PRTY_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_SBTYPE, FALLBACK (
EV_SBTYPE_CD INTEGER NOT NULL ,
EV_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ITEM_TYPE, FALLBACK (
ITEM_TYPE_CD INTEGER NOT NULL ,
ITEM_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ITEM_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.CARE_PLN_EV_TYPE, FALLBACK (
CARE_PLN_EV_TYPE_CD INTEGER NOT NULL ,
CARE_PLN_EV_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CARE_PLN_EV_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_STS_RSN, FALLBACK (
EV_STS_RSN_CD INTEGER NOT NULL ,
EV_STS_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_STS_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_STS_TYPE, FALLBACK (
EV_STS_TYPE_CD INTEGER NOT NULL ,
EV_STS_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_STS_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_CTGY, FALLBACK (
EV_CTGY_CD INTEGER NOT NULL ,
EV_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_RSN, FALLBACK (
EV_RSN_CD INTEGER NOT NULL ,
EV_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_RSOLUT_TYPE, FALLBACK (
EV_RSOLUT_CD INTEGER NOT NULL ,
EV_RSOLUT_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_RSOLUT_CD); 

CREATE SET TABLE GPROD1T_BASE.ITEM_SBTYPE, FALLBACK (
ITEM_SBTYPE_CD INTEGER NOT NULL ,
ITEM_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ITEM_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.QUES_FMT, FALLBACK (
QUES_FMT_CD INTEGER NOT NULL ,
QUES_FMT_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (QUES_FMT_CD); 

CREATE SET TABLE GPROD1T_BASE.QUES_CTGY, FALLBACK (
QUES_CTGY_CD INTEGER NOT NULL ,
QUES_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (QUES_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.CARE_PLN_TYPE, FALLBACK (
CARE_PLN_TYPE_CD INTEGER NOT NULL ,
CARE_PLN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CARE_PLN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ITEM, FALLBACK (
ITEM_ID INTEGER NOT NULL ,
ITEM_TYPE_CD INTEGER ,
ITEM_SBTYPE_CD INTEGER ,
ITEM_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ITEM_STRT_DT DATE ,
ITEM_END_DT DATE ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ITEM_ID); 

CREATE SET TABLE GPROD1T_BASE.QUES_GRP, FALLBACK (
QUES_GRP_CD INTEGER NOT NULL ,
QUES_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (QUES_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.TXT_TYPE, FALLBACK (
TXT_TYPE_CD INTEGER NOT NULL ,
TXT_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (TXT_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_STRC_TYPE, FALLBACK (
PRTY_STRC_TYPE_CD INTEGER NOT NULL ,
PRTY_STRC_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_STRC_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_INVLVMT_SBTYPE, FALLBACK (
ACCT_INVLVMT_SBTYPE_CD INTEGER NOT NULL ,
ACCT_INVLVMT_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_INVLVMT_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.OCPTN_SECTR, FALLBACK (
OCPTN_SECTR_CD INTEGER NOT NULL ,
OCPTN_SECTR_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (OCPTN_SECTR_CD); 

CREATE SET TABLE GPROD1T_BASE.OCPTN_STS, FALLBACK (
OCPTN_STS_CD INTEGER NOT NULL ,
OCPTN_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (OCPTN_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_STS_RSN, FALLBACK (
ACCT_STS_RSN_CD INTEGER NOT NULL ,
ACCT_STS_RSN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ACCT_STS_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_STS_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.MIL_STS, FALLBACK (
MIL_STS_CD INTEGER NOT NULL ,
MIL_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (MIL_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.CRTFTN_TYPE, FALLBACK (
CRTFTN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
CRTFTN_TYPE_CD INTEGER NOT NULL ,
CRTFTN_GRP_CD INTEGER NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CRTFTN_TYPE_CD,CRTFTN_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.ELCTRNC_ADDR_SBTYPE, FALLBACK (
ELCTRNC_ADDR_SBTYPE_CD INTEGER NOT NULL ,
ELCTRNC_ADDR_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ELCTRNC_ADDR_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.LANG, FALLBACK (
LANG_CD INTEGER NOT NULL ,
LANG_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ISO_LANG_CD INTEGER ,
LANG_NATV_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
LANG_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LANG_CD); 

CREATE SET TABLE GPROD1T_BASE.LANG_PRFCNCY_TYPE, FALLBACK (
LANG_PRFCNCY_TYPE_CD INTEGER NOT NULL ,
LANG_PRFCNCY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LANG_PRFCNCY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.DSABLY_CTGY_TYPE, FALLBACK (
DSABLY_CTGY_TYPE_CD INTEGER NOT NULL ,
DSABLY_CTGY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DSABLY_CTGY_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_GRP_RSN, FALLBACK (
PRTY_GRP_RSN_CD INTEGER NOT NULL ,
PRTY_GRP_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_GRP_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_LOCTR_USGE_TYPE, FALLBACK (
PRJ_LOCTR_USGE_TYPE_CD VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
PRJ_LOCTR_USGE_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_LOCTR_USGE_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_TYPE, FALLBACK (
PRJ_TYPE_CD INTEGER NOT NULL ,
PRJ_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_STS_XREF_TYPE, FALLBACK (
PRJ_STS_XREF_TYPE_CD INTEGER NOT NULL ,
PRJ_STS_XREF_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_STS_XREF_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_STS, FALLBACK (
PRJ_STS_CD INTEGER NOT NULL ,
PRJ_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_STS_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_SBTYPE, FALLBACK (
PRJ_SBTYPE_CD INTEGER NOT NULL ,
PRJ_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRJ_SBTYPE_NAME VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_CLASFCN_TYPE, FALLBACK (
PRJ_CLASFCN_TYPE_CD INTEGER NOT NULL ,
PRJ_CLASFCN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_CLASFCN_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_EV_TYPE, FALLBACK (
PRJ_EV_TYPE_CD INTEGER NOT NULL ,
PRJ_EV_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_EV_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_ASSET_CTGY_TYPE, FALLBACK (
PRTY_ASSET_CTGY_TYPE_CD INTEGER NOT NULL ,
PRTY_ASSET_CTGY_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_ASSET_CTGY_TYPE_CD); 

--Error: Table AGMT_EV_TYPE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.AGMT_EV_TYPE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.PRTY_AGMT_ROLE, FALLBACK (
PRTY_AGMT_ROLE_CD INTEGER NOT NULL ,
PRTY_AGMT_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_AGMT_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.LOAN_EV_SBTYPE, FALLBACK (
LOAN_EV_SBTYPE_CD INTEGER NOT NULL ,
LOAN_EV_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (LOAN_EV_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.EV_FEAT_VAL, FALLBACK (
EV_FEAT_VAL_CD INTEGER NOT NULL ,
EV_FEAT_VAL_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (EV_FEAT_VAL_CD); 

CREATE SET TABLE GPROD1T_BASE.ACCT_FEAT_VAL, FALLBACK (
ACCT_FEAT_VAL_CD INTEGER NOT NULL ,
ACCT_FEAT_VAL_NAME VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
ACCT_FEAT_VAL_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ACCT_FEAT_VAL_CD); 

--Error: Table AGMT_FEAT_VAL Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.AGMT_FEAT_VAL, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.SBSCRPN_TYPE, FALLBACK (
SBSCRPN_TYPE_CD INTEGER NOT NULL ,
SBSCRPN_TYPE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
SBSCRPN_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SBSCRPN_TYPE_CD); 

--Error: Table LOC_RLTD_ROLE Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.LOC_RLTD_ROLE, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.AGMT_LOC_ROLE_TYPE, FALLBACK (
AGMT_LOC_ROLE_TYPE_CD INTEGER NOT NULL ,
AGMT_LOC_ROLE_TYPE_NAME VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
AGMT_LOC_ROLE_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_LOC_ROLE_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.AGMT_STS_CTGY_TYPE, FALLBACK (
AGMT_STS_CTGY_CD INTEGER NOT NULL ,
AGMT_STS_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_STS_CTGY_CD); 

--Error: Table AGMT_STS_RSN Not Found in Core tables. Can't generate its ddl. 
CREATE SET TABLE GPROD1T_BASE.AGMT_STS_RSN, FALLBACK (
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (); 

CREATE SET TABLE GPROD1T_BASE.DEMOG_VAL, FALLBACK (
DEMOG_RNG_STRT_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_RNG_END_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC ,
DEMOG_VAL_CD INTEGER NOT NULL ,
DEMOG_CD INTEGER NOT NULL ,
VAL_UOM_CD INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (DEMOG_VAL_CD,DEMOG_CD); 

CREATE SET TABLE GPROD1T_BASE.SALRY_WG_CTGY, FALLBACK (
SALRY_WG_CTGY_CD INTEGER NOT NULL ,
SALRY_WG_CTGY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SALRY_WG_CTGY_CD); 

CREATE SET TABLE GPROD1T_BASE.CURY, FALLBACK (
CURY_CD INTEGER NOT NULL ,
CURY_NAME VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
CURY_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (CURY_CD); 

CREATE SET TABLE GPROD1T_BASE.ASSET_FEAT_VAL, FALLBACK (
ASSET_FEAT_VAL_CD INTEGER NOT NULL ,
ASSET_FEAT_VAL_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ASSET_FEAT_VAL_CD); 

CREATE SET TABLE GPROD1T_BASE.SIC, FALLBACK (
SIC_CD INTEGER NOT NULL ,
SIC_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
SIC_TYPE_ID INTEGER ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SIC_CD); 

CREATE SET TABLE GPROD1T_BASE.SIC_TYPE, FALLBACK (
SIC_TYPE_ID INTEGER NOT NULL ,
SIC_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (SIC_TYPE_ID); 

CREATE SET TABLE GPROD1T_BASE.PRTY_DOC_RSN, FALLBACK (
PRTY_DOC_RSN_CD INTEGER NOT NULL ,
PRTY_DOC_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_DOC_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_PRJ_ROLE, FALLBACK (
PRTY_PRJ_ROLE_CD INTEGER NOT NULL ,
PRTY_PRJ_ROLE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_PRJ_ROLE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_COST_GRP, FALLBACK (
PRJ_COST_GRP_CD INTEGER NOT NULL ,
PRJ_COST_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_COST_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.PRJ_FEAT_VAL, FALLBACK (
PRJ_FEAT_VAL_CD INTEGER NOT NULL ,
PRJ_FEAT_VAL_NAME VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
PRJ_FEAT_VAL_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRJ_FEAT_VAL_CD); 

CREATE SET TABLE GPROD1T_BASE.PRTY_STS_RSN, FALLBACK (
PRTY_STS_RSN_CD INTEGER NOT NULL ,
PRTY_STS_RSN_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRTY_STS_RSN_CD); 

CREATE SET TABLE GPROD1T_BASE.AGMT_SBTYPE, FALLBACK (
AGMT_SBTYPE_CD INTEGER NOT NULL ,
AGMT_SBTYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_SBTYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.PRPS_GRP, FALLBACK (
PRPS_GRP_CD INTEGER NOT NULL ,
PRPS_GRP_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (PRPS_GRP_CD); 

CREATE SET TABLE GPROD1T_BASE.ORG_SIC_TYPE, FALLBACK (
ORG_SIC_TYPE_CD INTEGER NOT NULL ,
ORG_SIC_TYPE_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (ORG_SIC_TYPE_CD); 

CREATE SET TABLE GPROD1T_BASE.AGMT_STS_TYPE, FALLBACK (
AGMT_STS_CD INTEGER NOT NULL ,
AGMT_STS_DESC VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC ,
Start_Ts	TIMESTAMP(6) WITH TIME ZONE 
,End_Ts	TIMESTAMP(6) WITH TIME ZONE 
,Start_Date	DATE FORMAT 'YYYY-MM-DD' 
,End_Date	DATE FORMAT 'YYYY-MM-DD' 
,Record_Deleted_Flag	BYTEINT 
,Ctl_Id	SMALLINT COMPRESS(997) 
,Process_Name	VARCHAR(128)
,Process_Id	INTEGER 
,Update_Process_Name	VARCHAR(128)
,Update_Process_Id	INTEGER 

) UNIQUE PRIMARY INDEX (AGMT_STS_CD); 

