REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY*/
/* Table mapping:	L1_PRTY_L0_VIRUS_C_TEAMS*/
/* Mapping group:	VIRUS_C_TEAMS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_TEAMS.SK_TEAM_ID AS INTEGER) AS PRTY_ID,
Cast (46 AS INTEGER) AS PRTY_SBTYPE_CD,
Cast (NULL AS VARCHAR(250)) AS PRTY_DESC,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS PRTY_STRT_DTTM,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS PRTY_END_DTTM,
Cast (31 AS INTEGER) AS INIT_DATA_SRC_CD,
Cast (2 AS INTEGER) AS PRTY_TYPE_CD,

 CAST('VIRUS_C_TEAMS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_L0_VIRUS_C_TEAMS'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_TEAMS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_TEAMS VIRUS_C_TEAMS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	ORG*/
/* Table mapping:	L1_ORG_L0_VIRUS_C_TEAMS*/
/* Mapping group:	VIRUS_C_TEAMS*/
/* Apply type:		UPSERTDELETE*/
Cast (VIRUS_C_TEAMS.SK_TEAM_ID AS INTEGER) AS ORG_PRTY_ID,
Cast (NULL AS INTEGER) AS PARNT_ORG_PRTY_ID,
Cast (22 AS INTEGER) AS ORG_SBTYPE_CD,
Cast (NULL AS INTEGER) AS LEGL_CLASFCN_CD,
Cast (NULL AS INTEGER) AS OWNRSHP_TYPE_CD,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS ORG_ESTBLD_DTTM,
Cast (31 AS INTEGER) AS DATA_SRC_CD,

 CAST('VIRUS_C_TEAMS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_ORG_L0_VIRUS_C_TEAMS'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_TEAMS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_TEAMS VIRUS_C_TEAMS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	ORG_NAME*/
/* Table mapping:	L1_ORG_NAME_L0_VIRUS_C_TEAMS*/
/* Mapping group:	VIRUS_C_TEAMS*/
/* Apply type:		UPSERTDELETE*/
Cast (VIRUS_C_TEAMS.SK_TEAM_ID AS INTEGER) AS ORG_PRTY_ID,
Cast (44 AS INTEGER) AS NAME_TYPE_CD,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS ORG_NAME_STRT_DT,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS ORG_NAME_END_DT,
Cast (VIRUS_C_TEAMS.TEAM_NAME AS VARCHAR(1000)) AS ORG_NAME,
Cast (NULL AS VARCHAR(250)) AS ORG_NAME_DESC,
Cast (31 AS INTEGER) AS DATA_SRC_CD,

 CAST('VIRUS_C_TEAMS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_ORG_NAME_L0_VIRUS_C_TEAMS'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_TEAMS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_TEAMS VIRUS_C_TEAMS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	LOCTR*/
/* Table mapping:	L1_LOCTR_L0_VIRUS_C_CITY*/
/* Mapping group:	VIRUS_C_CITY*/
/* Apply type:		UPSERTDELETE*/
Cast (VIRUS_C_CITY.SK_CITY_ID AS INTEGER) AS LOCTR_ID,
Cast (10 AS INTEGER) AS LOCTR_SBTYPE_CD,

 CAST('VIRUS_C_CITY' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_CITY'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_CITY.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_CITY VIRUS_C_CITY
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	GEOGRCL_AREA*/
/* Table mapping:	L1_GEOGRCL_AREA_L0_VIRUS_C_CITY*/
/* Mapping group:	VIRUS_C_CITY*/
/* Apply type:		UPSERTDELETE*/
Cast (VIRUS_C_CITY.SK_CITY_ID AS INTEGER) AS GEOGRCL_AREA_ID,
Cast (9 AS INTEGER) AS GEOGRCL_AREA_SBTYPE_CD,
Cast (NULL AS VARCHAR(1000)) AS GEOGRCL_AREA_SHRT_NAME,
Cast (VIRUS_C_CITY.CITY_NAME AS VARCHAR(2000)) AS GEOGRCL_AREA_NAME,
Cast (NULL AS VARCHAR(1000)) AS GEOGRCL_AREA_DESC,

 CAST('VIRUS_C_CITY' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_GEOGRCL_AREA_L0_VIRUS_C_CITY'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_CITY.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_CITY VIRUS_C_CITY
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	GEOGRCL_AREA_RLTD*/
/* Table mapping:	L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY*/
/* Mapping group:	VIRUS_C_CITY*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_CITY.SK_CITY_ID AS INTEGER) AS GEOGRCL_AREA_ID,
Cast (VIRUS_C_GOVERNORATE.SK_GOVERNORATE_CSO_CODE AS INTEGER) AS RLTD_GEOGRCL_AREA_ID,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS GEOGRCL_AREA_STRT_DTTM,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS GEOGRCL_AREA_END_DTTM,
Cast (5 AS INTEGER) AS GEOGRCL_AREA_RLTD_ROLE_ID,

 CAST('VIRUS_C_CITY' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_GEOGRCL_AREA_RLTD_L0_VIRUS_C_CITY'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_CITY.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_CITY VIRUS_C_CITY
JOIN GPROD1V_SRCI.VIRUS_C_GOVERNORATE
ON VIRUS_C_GOVERNORATE.GOVERNORATE_ID=VIRUS_C_CITY.GOVERNORATE_ID
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY_LOCTR*/
/* Table mapping:	L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY*/
/* Mapping group:	VIRUS_C_TEAMS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_TEAMS.SK_TEAM_ID AS INTEGER) AS PRTY_ID,
Cast (VIRUS_C_TEAMS.SK_CITY_ID AS INTEGER) AS LOCTR_ID,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS PRTY_LOCTR_STRT_DTTM,
Cast (59 AS INTEGER) AS PRTY_LOCTR_USGE_CD,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS PRTY_LOCTR_END_DTTM,

 CAST('VIRUS_C_TEAMS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_TEAMS_CITY'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_TEAMS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_TEAMS VIRUS_C_TEAMS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY*/
/* Table mapping:	L1_PRTY_L0_VIRUS_C_PERSON_DETAILS*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS PRTY_ID,
Cast (1 AS INTEGER) AS PRTY_SBTYPE_CD,
Cast (NULL AS VARCHAR(250)) AS PRTY_DESC,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS PRTY_STRT_DTTM,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS PRTY_END_DTTM,
Cast (31 AS INTEGER) AS INIT_DATA_SRC_CD,
Cast (1 AS INTEGER) AS PRTY_TYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_L0_VIRUS_C_PERSON_DETAILS'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_NAME*/
/* Table mapping:	L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		UPSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (49 AS INTEGER) AS NAME_TYPE_CD,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS INDIV_NAME_STRT_DT,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS INDIV_NAME_END_DT,
Cast (NULL AS VARCHAR(100)) AS GVN_NAME,
Cast (NULL AS VARCHAR(100)) AS MDL_NAME,
Cast (NULL AS VARCHAR(100)) AS FMLY_NAME,
Cast (NULL AS VARCHAR(1000)) AS NAME_PREFIX_TXT,
Cast (NULL AS VARCHAR(1000)) AS NAME_SFX_TXT,
Cast (31 AS INTEGER) AS DATA_SRC_CD,
Cast ("NAME" AS VARCHAR(2000)) AS FULL_NAME,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_NAME_L0_VIRUS_C_PERSON_DETAILS'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	LOCTR*/
/* Table mapping:	L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_MOBILE_NUMBER AS INTEGER) AS LOCTR_ID,
Cast (2 AS INTEGER) AS LOCTR_SBTYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where MOBILE_NUMBER IS NOT NULL AND MOBILE_NUMBER <> '';


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	ADDR*/
/* Table mapping:	L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_MOBILE_NUMBER AS INTEGER) AS ADDR_ID,
Cast (5 AS INTEGER) AS ADDR_SBTYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_ADDR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where MOBILE_NUMBER IS NOT NULL AND MOBILE_NUMBER <> '';


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	TLPHN_NUM*/
/* Table mapping:	L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_MOBILE_NUMBER AS INTEGER) AS TLPHN_NUM_ID,
Cast (VIRUS_C_PERSON_DETAILS.MOBILE_NUMBER AS VARCHAR(100)) AS TLPHN_NUM,
Cast (NULL AS VARCHAR(50)) AS TLPHN_CTRY_CD_NUM,
Cast (NULL AS VARCHAR(50)) AS TLPHN_AREA_CD_NUM,
Cast (NULL AS VARCHAR(50)) AS TLPHN_EXCH_NUM,
Cast (NULL AS VARCHAR(100)) AS TLPHN_LN_NUM,
Cast (NULL AS VARCHAR(50)) AS TLPHN_EXTN_NUM,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_TLPHN_NUM_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where MOBILE_NUMBER IS NOT NULL AND MOBILE_NUMBER <> '';


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY_LOCTR*/
/* Table mapping:	L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.SK_MOBILE_NUMBER AS INTEGER) AS LOCTR_ID,
Cast (DATE '1900-01-01' AS TIMESTAMP(0)) AS PRTY_LOCTR_STRT_DTTM,
Cast (62 AS INTEGER) AS PRTY_LOCTR_USGE_CD,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS PRTY_LOCTR_END_DTTM,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_LOCTR_L0_VIRUS_C_PERSON_DETAILS_MOBILE_NUMBER'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where MOBILE_NUMBER IS NOT NULL AND MOBILE_NUMBER <> '';


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY_RLTD*/
/* Table mapping:	L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.SK_TEAM_ID AS INTEGER) AS RLTD_PRTY_ID,
Cast (89 AS INTEGER) AS RLTD_ROLE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS TIMESTAMP(0)) AS PRTY_RLTD_STRT_DTTM,
Cast (DATE '2900-12-31' AS TIMESTAMP(0)) AS PRTY_RLTD_END_DTTM,
Cast (NULL AS INTEGER) AS RLTD_STS_RSN_CD,
Cast (NULL AS INTEGER) AS RLTD_STS_TYPE_CD,
Cast (NULL AS INTEGER) AS PRTY_STRC_TYPE_CD,
Cast (31 AS INTEGER) AS DATA_SRC_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_RLTD_L0_VIRUS_C_PERSON_TEAM'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where TEAM_ID IS NOT NULL;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_DISEASE_STS*/
/* Table mapping:	L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.SK_DIABETIC_FLAG AS INTEGER) AS DISEASE_REGISTRY_ID,
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS DISEASE_STS_STRT_DT,
Cast (DATE '2900-12-31' AS DATE) AS DISEASE_STS_END_DT,
Cast (CASE WHEN DIABETIC_FLAG=0 THEN '1' WHEN DIABETIC_FLAG=1 THEN '2' END AS INTEGER) AS DISEASE_STS_TYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_DIABETIC_FLAG'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where DIABETIC_FLAG IS NOT NULL;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_DISEASE_STS*/
/* Table mapping:	L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.SK_HYPERTENSIVE_FLAG AS INTEGER) AS DISEASE_REGISTRY_ID,
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS DISEASE_STS_STRT_DT,
Cast (DATE '2900-12-31' AS DATE) AS DISEASE_STS_END_DT,
Cast (CASE WHEN HYPERTENSIVE_FLAG=0 THEN '1' WHEN HYPERTENSIVE_FLAG=1 THEN '2' END AS INTEGER) AS DISEASE_STS_TYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_HYPERTENSIVE_FLAG'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where HYPERTENSIVE_FLAG IS NOT NULL;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_DISEASE_STS*/
/* Table mapping:	L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS DISEASE_STS_STRT_DT,
Cast (DATE '2900-12-31' AS DATE) AS DISEASE_STS_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.SK_SCAN_RESULT AS INTEGER) AS DISEASE_REGISTRY_ID,
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (CASE WHEN SCAN_RESULT= 0 THEN 1 WHEN SCAN_RESULT=1 THEN 2 WHEN SCAN_RESULT=3 THEN 3 END AS INTEGER) AS DISEASE_STS_TYPE_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_DISEASE_STS_L0_VIRUS_C_PERSON_DETAILS_SCAN_RESULT'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
Where SCAN_RESULT IS NOT NULL;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (1 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.LOW_PRESSURE AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (10 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_LOW_PRESSURE'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (2 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.HIGH_PRESSURE AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (10 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HIGH_PRESSURE'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (3 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.BODY_MASS_INDICATOR AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (11 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_MASS_INDICATOR'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (4 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.BODY_DIABETES_RESULT AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (12 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_BODY_DIABETES_RESULT'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (5 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.HEIGHT AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (13 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_HEIGHT'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	INDIV_MEDCL_MSR*/
/* Table mapping:	L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (31 AS INTEGER) AS DATA_SRC_TYPE_CD,
Cast (6 AS INTEGER) AS MEDCL_MSR_TYPE_CD,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS MEDCL_HIST_DT,
Cast (DATE '2900-12-31' AS DATE) AS MEDCL_HIST_END_DT,
Cast (VIRUS_C_PERSON_DETAILS.WEIGHT AS VARCHAR(100)) AS MEDCL_MSR_VAL,
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS INDIV_PRTY_ID,
Cast (14 AS INTEGER) AS MEDCL_MSR_UOM_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_INDIV_MEDCL_MSR_L0_VIRUS_C_PERSON_DETAILS_WEIGHT'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	DEMOG*/
/* Table mapping:	L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		INSERT*/
Cast (4 AS INTEGER) AS DEMOG_CD,
Cast (NULL AS VARCHAR(250)) AS DEMOG_DESC,
Cast (2 AS INTEGER) AS DEMOG_GRP_CD,
Cast ('مؤشر التأمين الحكومي للشخص في Virus C' AS VARCHAR(100)) AS DEMOG_NAME,
Cast (NULL AS INTEGER) AS SRC_ORG_PRTY_ID,
Cast (31 AS INTEGER) AS DATA_SRC_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


REPLACE VIEW GPROD1V_INP.TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG_IN AS LOCK ROW FOR ACCESS
SELECT 
/* Target table:	PRTY_DEMOG*/
/* Table mapping:	L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG*/
/* Mapping group:	VIRUS_C_PERSON_DETAILS*/
/* Apply type:		HISTORY*/
Cast (VIRUS_C_PERSON_DETAILS.SK_NATIONAL_ID AS INTEGER) AS PRTY_ID,
Cast (VIRUS_C_PERSON_DETAILS.ENTRY_DATE_TIME AS DATE) AS PRTY_DEMOG_STRT_DT,
Cast (DATE '2900-12-31' AS DATE) AS PRTY_DEMOG_END_DT,
Cast (NULL AS INTEGER) AS DEMOG_VAL_CD,
Cast (CASE WHEN  HEALTH_INSURANCE_FLAG='0' THEN 'غير مؤمن عليه حكوميا' WHEN HEALTH_INSURANCE_FLAG='1' THEN 'مؤمن علية حكوميا' AS VARCHAR(100)) AS DEMOG_VAL,
Cast (31 AS INTEGER) AS DATA_SRC_CD,
Cast (4 AS INTEGER) AS DEMOG_CD,

 CAST('VIRUS_C_PERSON_DETAILS' AS VARCHAR(100)) AS  MAP_GROUP ,
(SELECT Business_Date FROM GPROD1V_GCFR.GCFR_Process_Id
   WHERE Process_Name = 'TXF_CORE_L1_PRTY_DEMOG_L0_VIRUS_C_PERSON_DETAILS_HEALTH_INSURANCE_FLAG'
) AS Start_Date,
DATE '9999-12-31' AS End_Date,
VIRUS_C_PERSON_DETAILS.MODIFICATION_TYPE

FROM GPROD1V_SRCI.VIRUS_C_PERSON_DETAILS VIRUS_C_PERSON_DETAILS
;


