---DUP_Test_Case_1---
SEL PRTY_ID FROM GPROD1T_BASE.PRTY GROUP BY PRTY_ID HAVING COUNT(*)>1;

---DUP_Test_Case_2---
SEL ORG_PRTY_ID FROM GPROD1T_BASE.ORG GROUP BY ORG_PRTY_ID HAVING COUNT(*)>1;

---DUP_Test_Case_3---
SEL ORG_PRTY_ID,NAME_TYPE_CD,ORG_NAME_STRT_DT,DATA_SRC_CD FROM GPROD1T_BASE.ORG_NAME GROUP BY ORG_PRTY_ID,NAME_TYPE_CD,ORG_NAME_STRT_DT,DATA_SRC_CD HAVING COUNT(*)>1;

---DUP_Test_Case_4---
SEL LOCTR_ID FROM GPROD1T_BASE.LOCTR GROUP BY LOCTR_ID HAVING COUNT(*)>1;

---DUP_Test_Case_5---
SEL GEOGRCL_AREA_ID FROM GPROD1T_BASE.GEOGRCL_AREA GROUP BY GEOGRCL_AREA_ID HAVING COUNT(*)>1;

---DUP_Test_Case_6---
SEL GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_STRT_DTTM,GEOGRCL_AREA_RLTD_ROLE_ID FROM GPROD1T_BASE.GEOGRCL_AREA_RLTD GROUP BY GEOGRCL_AREA_ID,RLTD_GEOGRCL_AREA_ID,GEOGRCL_AREA_STRT_DTTM,GEOGRCL_AREA_RLTD_ROLE_ID HAVING COUNT(*)>1;

---DUP_Test_Case_7---
SEL PRTY_ID,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,PRTY_LOCTR_USGE_CD FROM GPROD1T_BASE.PRTY_LOCTR GROUP BY PRTY_ID,LOCTR_ID,PRTY_LOCTR_STRT_DTTM,PRTY_LOCTR_USGE_CD HAVING COUNT(*)>1;

---DUP_Test_Case_8---
SEL INDIV_PRTY_ID,NAME_TYPE_CD,INDIV_NAME_STRT_DT,DATA_SRC_CD FROM GPROD1T_BASE.INDIV_NAME GROUP BY INDIV_PRTY_ID,NAME_TYPE_CD,INDIV_NAME_STRT_DT,DATA_SRC_CD HAVING COUNT(*)>1;

---DUP_Test_Case_9---
SEL ADDR_ID FROM GPROD1T_BASE.ADDR GROUP BY ADDR_ID HAVING COUNT(*)>1;

---DUP_Test_Case_10---
SEL TLPHN_NUM_ID FROM GPROD1T_BASE.TLPHN_NUM GROUP BY TLPHN_NUM_ID HAVING COUNT(*)>1;

---DUP_Test_Case_11---
SEL PRTY_ID,RLTD_PRTY_ID,RLTD_ROLE_CD,PRTY_RLTD_STRT_DTTM,DATA_SRC_CD FROM GPROD1T_BASE.PRTY_RLTD GROUP BY PRTY_ID,RLTD_PRTY_ID,RLTD_ROLE_CD,PRTY_RLTD_STRT_DTTM,DATA_SRC_CD HAVING COUNT(*)>1;

---DUP_Test_Case_12---
SEL DISEASE_STS_STRT_DT,INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD FROM GPROD1T_BASE.INDIV_DISEASE_STS GROUP BY DISEASE_STS_STRT_DT,INDIV_PRTY_ID,DISEASE_REGISTRY_ID,DATA_SRC_TYPE_CD,DISEASE_STS_TYPE_CD HAVING COUNT(*)>1;

---DUP_Test_Case_13---
SEL DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,MEDCL_HIST_DT,INDIV_PRTY_ID FROM GPROD1T_BASE.INDIV_MEDCL_MSR GROUP BY DATA_SRC_TYPE_CD,MEDCL_MSR_TYPE_CD,MEDCL_HIST_DT,INDIV_PRTY_ID HAVING COUNT(*)>1;

---DUP_Test_Case_14---
SEL DEMOG_CD FROM GPROD1T_BASE.DEMOG GROUP BY DEMOG_CD HAVING COUNT(*)>1;

---DUP_Test_Case_15---
SEL PRTY_ID,DEMOG_CD,PRTY_DEMOG_STRT_DT FROM GPROD1T_BASE.PRTY_DEMOG GROUP BY PRTY_ID,DEMOG_CD,PRTY_DEMOG_STRT_DT HAVING COUNT(*)>1;

